package com.cuvar.app;

/**
 * Banka pitanja za otključavanje. Svako pitanje je jedan red:
 *   "Pitanje|tačan odgovor|netačan|netačan|netačan"  (ponuđeni odgovori, redosled se meša)
 *   "Pitanje|broj"                                    (odgovor je broj koji se kuca)
 * Novo pitanje se dodaje kao novi red u odgovarajuću grupu. Nova grupa se dodaje u NAMES i GROUPS.
 * tests/com/cuvar/app/QuizTest.java proverava da je svaki red ispravno zapisan.
 */
final class QuizBank {

    private QuizBank() {
    }

    static final String[] ZAGONETKE = {
            "Ima zube, a ne jede. Šta je to?|češalj|kašika|olovka|čaša",
            "Što se više suši, to je mokriji. Šta je to?|peškir|kišobran|jastuk|lonac",
            "Ima dirke, a ne otvara nijedna vrata. Šta je to?|klavir|kapija|brava|ormar",
            "Kuca, a nije srce; ide, a nema noge. Šta je to?|sat|voz|bubanj|čekić",
            "Ima glavu i rep, a nema telo. Šta je to?|novčić|zmija|crv|miš",
            "Što više uzmeš, to više ostavljaš za sobom. Šta je to?|koraci|novac|vreme|hrana",
            "Ima jedno oko, a ne vidi. Šta je to?|igla|dugme|ključ|olovka",
            "Što je ima više, to manje vidiš. Šta je to?|mrak|svetlost|kuća|planina",
            "Leti bez krila, plače bez očiju. Šta je to?|oblak|ptica|avion|vetar",
            "Raste naopačke, glavom nadole. Šta je to?|ledenica|drvo|cvet|trava",
            "Ima vrat, a nema glavu. Šta je to?|flaša|žirafa|lampa|stolica",
            "Ima četiri noge, a ne hoda. Šta je to?|sto|pas|mačka|pauk",
            "Puno rupa, a ipak drži vodu. Šta je to?|sunđer|sito|kofa|lonac",
            "Pripada tebi, a drugi ga koriste više nego ti. Šta je to?|ime|telefon|automobil|kuća",
            "Čim izgovoriš njeno ime, nestane. Šta je to?|tišina|tajna|eho|senka",
            "Ide gore i dole, a ne pomera se s mesta. Šta je to?|stepenice|lift|klackalica|lopta",
            "Ima gradove bez kuća, reke bez vode i šume bez drveća. Šta je to?|mapa|pustinja|slika|knjiga",
            "Ujutru hoda na četiri noge, u podne na dve, a uveče na tri. Ko je to?|čovek|pas|konj|ptica",
            "Ima lice i dve ruke, a nema nogu. Šta je to?|sat|lutka|robot|statua",
            "Vodi kroz grad i polja, a nikad se ne pomeri. Šta je to?|put|reka|voz|vetar",
            "Okruglo i žuto, greje, a daleko je. Šta je to?|sunce|mesec|lopta|limun",
            "Polje belo, seme crno; ko ga seje, taj i zna. Šta je to?|knjiga|sneg|šahovska tabla|njiva",
            "I zimi i leti isto je obučena. Šta je to?|jelka|hrast|lipa|breza",
            "Spolja zelena, iznutra crvena, a seme crno. Šta je to?|lubenica|paradajz|jabuka|krastavac",
            "Ima šešir, a nema glavu; ima nogu, a nema cipelu. Šta je to?|pečurka|ekser|kišobran|lampa",
            "Ima krila, a nije ptica; leti, a nije živo. Šta je to?|avion|leptir|pčela|šišmiš",
            "Lakše je od pera, a niko ga ne može zadržati ni par minuta. Šta je to?|dah|kamen|olovka|knjiga",
            "Može da se slomi, a da ga niko ni ne dotakne. Šta je to?|obećanje|staklo|tanjir|jaje",
            "Otvara se kad pada kiša. Šta je to?|kišobran|prozor|cvet|knjiga",
            "Uvek je ispred tebe, a ne možeš je videti. Šta je to?|budućnost|nos|ogledalo|senka",
            "Ima oči, a ne vidi; raste u zemlji. Šta je to?|krompir|šargarepa|crv|koren",
            "Dan i noć stoji pred kućom, ne jede i ne spava, a čuva. Šta je to?|ograda|pas|mačka|stražar",
            "Belo kao sneg, a nije sneg; slatko kao med, a nije med. Šta je to?|šećer|so|brašno|mleko",
            "Bez nogu ide, bez ruku vrata otvara. Šta je to?|vetar|voda|duh|mačka",
            "Ide u vodu, a ne pokvasi se. Šta je to?|senka|riba|kamen|čamac",
            "Sto braće u jednoj kući spava. Šta je to?|šibice|zubi|olovke|pčele",
            "Nema noge, a trči; nema usta, a žubori. Šta je to?|potok|vetar|sat|voz",
            "Svako ga ima, a niko ga ne može prodati ni pokloniti. Šta je to?|senka|novac|kuća|igračka",
            "Jede, a nikad nije sit; pije vodu i umre. Šta je to?|vatra|pas|biljka|riba",
            "Ima mnogo listova, a nije drvo. Šta je to?|knjiga|kupus|salata|novine",
            "Kad se rodi, veliko je; kad ostari, malo je. Šta je to?|sveća|drvo|čovek|reka",
            "Šta se nalazi u sredini Pariza?|slovo R|Ajfelov toranj|Sena|Luvr",
            "Čega ima jednom u minutu, dva puta u momentu, a nijednom u sto godina?|slova M|sekunde|sata|dana",
    };

    static final String[] PITALICE = {
            "Šta je teže: kilogram perja ili kilogram gvožđa?|isto su teški|perje|gvožđe|zavisi od vetra",
            "Ako u trci prestigneš drugog, koji si?|drugi|prvi|treći|poslednji",
            "Petar ima tri ćerke, a svaka ima po jednog brata. Koliko dece ima Petar?|4",
            "Koliko meseci u godini ima 28 dana?|12",
            "Koliko jaja možeš da pojedeš na prazan stomak?|1",
            "Električni voz ide na sever, a vetar duva na jug. Na koju stranu ide dim?|nema dima|na sever|na jug|na istok",
            "Koje boje je takozvana crna kutija u avionu?|narandžasta|crna|bela|siva",
            "Koliko je životinja Mojsije poveo u barku?|nijednu, to je bio Noje|po dve od svake|sedam|stotinu",
            "Seljak ima 17 ovaca. Sve osim 9 su pobegle. Koliko mu je ostalo?|9",
            "Imaš 3 jabuke i uzmeš 2. Koliko jabuka ti imaš?|2",
            "Lekar ti da 3 tablete i kaže da piješ jednu na svakih pola sata. Za koliko minuta ćeš popiti sve?|60",
            "Koliko puta možeš da oduzmeš 5 od 25?|1",
            "Koja reč je u rečniku uvek napisana pogrešno?|pogrešno|tačno|rečnik|nijedna",
            "U mračnoj sobi imaš šibicu, sveću, lampu na ulje i peć. Šta prvo pališ?|šibicu|sveću|lampu|peć",
            "Šta se nalazi između neba i zemlje?|slovo I|vazduh|oblaci|ptice",
            "Kada je 10 + 3 = 1?|kad gledaš na sat|nikada|u ponoć|kad je prestupna godina",
            "Petao snese jaje na vrh krova. Na koju stranu jaje padne?|petao ne nosi jaja|levo|desno|ostaje na krovu",
            "Šta možeš da držiš u desnoj ruci, a nikako u levoj?|levi lakat|olovku|loptu|telefon",
            "Koliko slova ima reč „azbuka“?|6",
            "Koliko je pola od pola od 100?|25",
            "Koliko je 2 + 2 × 2?|6",
            "Koliko nogu imaju dve kokoške i tri psa zajedno?|16",
            "Polovina broja je 15. Koji je to broj?|30",
            "Brat i sestra imaju zajedno 10 godina, a brat je stariji 4 godine. Koliko godina ima sestra?|3",
            "Puž se penje uz stub od 10 metara: danju 3 m gore, noću 2 m dole. Kog dana stiže na vrh?|8",
            "Ako 5 mašina za 5 minuta napravi 5 proizvoda, za koliko minuta 100 mašina napravi 100 proizvoda?|5",
            "Lopta i palica koštaju 110 dinara. Palica je skuplja od lopte 100 dinara. Koliko košta lopta?|5",
    };

    static final String[] OPSTA_KULTURA = {
            "Ko je naslikao Mona Lizu?|Leonardo da Vinči|Mikelanđelo|Pablo Pikaso|Vinsent van Gog",
            "Ko je naslikao „Zvezdanu noć“?|Vinsent van Gog|Klod Mone|Salvador Dali|Rembrant",
            "Ko je oslikao tavanicu Sikstinske kapele?|Mikelanđelo|Rafaelo|Leonardo da Vinči|Botičeli",
            "Ko je komponovao „Mesečevu sonatu“?|Ludvig van Betoven|Volfgang Amadeus Mocart|Johan Sebastijan Bah|Frederik Šopen",
            "Ko je komponovao operu „Čarobna frula“?|Volfgang Amadeus Mocart|Đuzepe Verdi|Ludvig van Betoven|Petar Iljič Čajkovski",
            "Ko je komponovao balet „Labudovo jezero“?|Petar Iljič Čajkovski|Igor Stravinski|Johan Štraus|Antonio Vivaldi",
            "Ko je komponovao „Četiri godišnja doba“?|Antonio Vivaldi|Johan Sebastijan Bah|Đuzepe Verdi|Franc Šubert",
            "Koliko žica ima obična gitara?|6",
            "Koliko dirki ima standardni klavir?|88",
            "Koliko boja ima duga?|7",
            "Koja boja nastaje mešanjem plave i žute?|zelena|ljubičasta|narandžasta|braon",
            "Koja boja nastaje mešanjem crvene i bele?|roze|ljubičasta|narandžasta|siva",
            "Koliko je godina u jednom veku?|100",
            "Koliko je godina u jednom milenijumu?|1000",
            "Koliko dana ima prestupna godina?|366",
            "Koliko sati ima jedna nedelja?|168",
            "Koliko sekundi ima jedan sat?|3600",
            "Koliko minuta ima jedan dan?|1440",
            "Koji mesec u godini ima najmanje dana?|februar|april|novembar|jun",
            "Koji je prvi dan proleća po kalendaru?|21. mart|1. mart|21. april|1. maj",
            "Ko je izmislio telefon (prvi patent)?|Aleksandar Grejem Bel|Nikola Tesla|Tomas Edison|Guljelmo Markoni",
            "Ko je formulisao teoriju relativnosti?|Albert Ajnštajn|Isak Njutn|Galileo Galilej|Nikola Tesla",
            "Ko je otkrio penicilin?|Aleksandar Fleming|Luj Paster|Marija Kiri|Čarls Darvin",
            "Ko je postavio teoriju evolucije prirodnom selekcijom?|Čarls Darvin|Gregor Mendel|Isak Njutn|Luj Paster",
            "Koja naučnica je dobila Nobelovu nagradu i za fiziku i za hemiju?|Marija Kiri|Ada Lavlejs|Rozalind Frenklin|Lize Majtner",
            "Ko je prvi kročio na Mesec?|Nil Armstrong|Jurij Gagarin|Baz Oldrin|Majkl Kolins",
            "Ko je bio prvi čovek u svemiru?|Jurij Gagarin|Nil Armstrong|Valentina Tereškova|Džon Glen",
            "Koje godine je čovek prvi put sleteo na Mesec?|1969",
            "Ko je otkrio Ameriku 1492. godine?|Kristofor Kolumbo|Vasko da Gama|Fernando Magelan|Marko Polo",
            "Na kom brodu je putovao Kolumbo kada je stigao do Amerike?|Santa Marija|Titanik|Mejflauer|Viktorija",
            "Koje godine je potonuo Titanik?|1912",
            "Koje godine je počeo Prvi svetski rat?|1914",
            "Koje godine je završen Drugi svetski rat?|1945",
            "Koje godine je pao Berlinski zid?|1989",
            "Koliko ima znakova Zodijaka?|12",
            "Iz koje zemlje potiče pica?|Italija|Grčka|Francuska|Španija",
            "Iz koje zemlje potiču suši?|Japan|Kina|Koreja|Tajland",
            "Iz koje zemlje potiče paela?|Španija|Italija|Portugalija|Meksiko",
            "Kako se zove čuveni muzej u Parizu u kome je Mona Liza?|Luvr|Prado|Ermitaž|Britanski muzej",
            "Koji je simbol mira?|golub sa maslinovom grančicom|orao|lav|soko",
            "Šta znači skraćenica „npr.“?|na primer|na pristojan red|nema problema|naš prijatelj",
            "Koliko karata ima standardni špil (bez džokera)?|52",
            "Koliko tačkica ukupno ima obična kockica za igru?|21",
            "Koliko figura ima svaki igrač na početku partije šaha?|16",
            "Kako se zove crtani lik, mornar koji jede spanać?|Popaj|Paja Patak|Miki Maus|Duško Dugouško",
            "Kako se zove Mikijev pas?|Pluton|Šilja|Dugouško|Tom",
            "Koliko patuljaka ima u bajci o Snežani?|7",
            "Ko je napisao bajku „Ružno pače“?|Hans Kristijan Andersen|braća Grim|Šarl Pero|Ezop",
            "Ko je napisao „Pepeljugu“ u verziji sa staklenom cipelicom?|Šarl Pero|Hans Kristijan Andersen|braća Grim|Ezop",
    };

    static final String[] KNJIZEVNOST = {
            "Ko je napisao „Na Drini ćuprija“?|Ivo Andrić|Meša Selimović|Branislav Nušić|Danilo Kiš",
            "Koji pisac sa ovih prostora je dobio Nobelovu nagradu za književnost 1961. godine?|Ivo Andrić|Miloš Crnjanski|Meša Selimović|Dobrica Ćosić",
            "Ko je napisao „Gorski vijenac“?|Petar II Petrović Njegoš|Vuk Karadžić|Laza Kostić|Jovan Jovanović Zmaj",
            "Ko je napisao „Derviš i smrt“?|Meša Selimović|Ivo Andrić|Borislav Pekić|Danilo Kiš",
            "Ko je napisao „Seobe“?|Miloš Crnjanski|Ivo Andrić|Borislav Pekić|Dobrica Ćosić",
            "Ko je napisao „Sumnjivo lice“?|Branislav Nušić|Jovan Sterija Popović|Stevan Sremac|Radoje Domanović",
            "Ko je napisao „Gospođu ministarku“?|Branislav Nušić|Jovan Sterija Popović|Borislav Stanković|Laza Lazarević",
            "Ko je napisao „Pop Ćira i pop Spira“?|Stevan Sremac|Branislav Nušić|Janko Veselinović|Simo Matavulj",
            "Ko je napisao „Nečistu krv“?|Borisav Stanković|Stevan Sremac|Ivo Andrić|Milovan Glišić",
            "Ko je napisao pesmu „Santa Maria della Salute“?|Laza Kostić|Jovan Dučić|Aleksa Šantić|Đura Jakšić",
            "Koji pesnik je deci poznat kao „Čika Jova“?|Jovan Jovanović Zmaj|Dušan Radović|Branko Ćopić|Desanka Maksimović",
            "Ko je napisala pesmu „Krvava bajka“?|Desanka Maksimović|Isidora Sekulić|Vesna Parun|Mira Alečković",
            "Ko je napisao „Orlovi rano lete“?|Branko Ćopić|Dušan Radović|Grigor Vitez|Ivo Andrić",
            "Ko je napisao „Hazarski rečnik“?|Milorad Pavić|Danilo Kiš|Borislav Pekić|David Albahari",
            "Ko je napisao „Grobnicu za Borisa Davidoviča“?|Danilo Kiš|Milorad Pavić|Ivo Andrić|Mihailo Lalić",
            "Ko je napisao „Kapetana Džona Piplfoksa“?|Dušan Kovačević|Branislav Nušić|Ljubomir Simović|Aleksandar Popović",
            "Ko je napisao „Maratonci trče počasni krug“?|Dušan Kovačević|Branislav Nušić|Ljubomir Simović|Borislav Pekić",
            "Ko je reformisao srpski jezik i azbuku?|Vuk Stefanović Karadžić|Dositej Obradović|Sveti Sava|Branko Radičević",
            "Po kom načelu je Vuk reformisao pravopis?|Piši kao što govoriš|Jedno slovo, dva glasa|Piši kako je lepo|Svaki glas dva slova",
            "Ko je napisao „Romea i Juliju“?|Vilijam Šekspir|Čarls Dikens|Johan Volfgang Gete|Dante Aligijeri",
            "Ko je napisao „Hamleta“?|Vilijam Šekspir|Kristofer Marlo|Molijer|Gete",
            "Ko je napisao „Don Kihota“?|Migel de Servantes|Lope de Vega|Dante Aligijeri|Viktor Igo",
            "Ko je napisao „Božanstvenu komediju“?|Dante Aligijeri|Đovani Bokačo|Frančesko Petrarka|Nikolo Makijaveli",
            "Ko je napisao „Rat i mir“?|Lav Tolstoj|Fjodor Dostojevski|Anton Čehov|Aleksandar Puškin",
            "Ko je napisao „Zločin i kaznu“?|Fjodor Dostojevski|Lav Tolstoj|Nikolaj Gogolj|Ivan Turgenjev",
            "Ko je napisao „Malog princa“?|Antoan de Sent Egziperi|Žil Vern|Viktor Igo|Alber Kami",
            "Ko je napisao „Jadnike“?|Viktor Igo|Onore de Balzak|Emil Zola|Aleksandar Dima",
            "Ko je napisao „Tri musketara“?|Aleksandar Dima|Viktor Igo|Žil Vern|Gistav Flober",
            "Ko je napisao „Put oko sveta za 80 dana“?|Žil Vern|Herbert Džordž Vels|Mark Tven|Aleksandar Dima",
            "Ko je napisao „Avanture Toma Sojera“?|Mark Tven|Džek London|Ernest Hemingvej|Čarls Dikens",
            "Ko je napisao „Starac i more“?|Ernest Hemingvej|Džon Stajnbek|Mark Tven|Herman Melvil",
            "Ko je napisao „Hari Potera“?|Džoan Ketlin Rouling|Džon Ronald Tolkin|Rold Dal|Klajv Stejpls Luis",
            "Ko je napisao „Gospodara prstenova“?|Džon Ronald Tolkin|Klajv Stejpls Luis|Džordž R. R. Martin|Džoan Ketlin Rouling",
            "Ko je napisao roman „1984“?|Džordž Orvel|Oldos Haksli|Rej Bredberi|Franc Kafka",
            "Ko je napisao „Proces“ i „Preobražaj“?|Franc Kafka|Herman Hese|Tomas Man|Alber Kami",
            "Ko je napisao „Ilijadu“ i „Odiseju“?|Homer|Sofokle|Platon|Ezop",
            "Ko je napisao „Fausta“?|Johan Volfgang Gete|Fridrih Šiler|Hajnrih Hajne|Tomas Man",
            "Ko je napisao „Anu Karenjinu“?|Lav Tolstoj|Fjodor Dostojevski|Anton Čehov|Maksim Gorki",
            "Kako se zove Don Kihotov verni pratilac?|Sančo Pansa|Rosinante|Dulsineja|Pinokio",
    };

    static final String[] PRIRODA = {
            "Koliko nogu ima pauk?|8",
            "Koliko nogu ima insekt?|6",
            "Koliko srca ima hobotnica?|3",
            "Koja je najveća životinja na svetu?|plavi kit|afrički slon|žirafa|bela ajkula",
            "Koja je najbrža kopnena životinja?|gepard|lav|konj|noj",
            "Koja od ovih ptica ne može da leti?|pingvin|orao|vrabac|golub",
            "Šta pčele prave od cvetnog nektara?|med|mleko|svilu|sir",
            "Koja životinja je najviša?|žirafa|slon|kamila|noj",
            "Koja životinja nosi mladunce u torbi?|kengur|medved|zec|majmun",
            "Kako se zove mladunče konja?|ždrebe|tele|jare|jagnje",
            "Kako se zove mladunče krave?|tele|ždrebe|jare|prase",
            "Kako se zove mladunče koze?|jare|jagnje|tele|štene",
            "Kako se zove mladunče ovce?|jagnje|jare|tele|ždrebe",
            "Šta jede panda najviše?|bambus|ribu|meso|travu",
            "Koja životinja menja boju da bi se sakrila?|kameleon|krokodil|kornjača|žaba",
            "Od čega se pravi svila?|od niti svilene bube|od pamuka|od vune|od lana",
            "Koliko krila ima pčela?|4",
            "Koliko očiju ima većina pauka?|8",
            "Šta je kit?|sisar|riba|gmizavac|vodozemac",
            "Šta je žaba?|vodozemac|gmizavac|sisar|riba",
            "Šta je slepi miš?|sisar|ptica|insekt|gmizavac",
            "Koji gas biljke koriste za fotosintezu?|ugljen-dioksid|kiseonik|azot|helijum",
            "Koji gas udišemo da bismo živeli?|kiseonik|ugljen-dioksid|azot|vodonik",
            "Koliko kostiju ima odrastao čovek?|206",
            "Koliko zuba ima odrastao čovek, sa umnjacima?|32",
            "Koji organ pumpa krv kroz telo?|srce|pluća|jetra|bubreg",
            "Koji je najveći organ ljudskog tela?|koža|jetra|mozak|pluća",
            "Koji organ prečišćava krv i stvara mokraću?|bubreg|srce|želudac|pluća",
            "Koliko komora ima ljudsko srce?|4",
            "Koja krvna grupa je univerzalni davalac?|0 negativna|AB pozitivna|A pozitivna|B negativna",
            "Koji vitamin telo stvara na suncu?|vitamin D|vitamin C|vitamin A|vitamin B12",
            "Kako se zove najmanja čestica hemijskog elementa?|atom|molekul|ćelija|kristal",
            "Hemijska formula vode je?|H2O|CO2|O2|NaCl",
            "Hemijski simbol zlata je?|Au|Ag|Zn|Fe",
            "Hemijski simbol srebra je?|Ag|Au|Si|Sr",
            "Hemijski simbol gvožđa je?|Fe|Au|G|Ir",
            "Hemijska formula kuhinjske soli je?|NaCl|H2O|CO2|KCl",
            "Koji metal je tečan na sobnoj temperaturi?|živa|olovo|aluminijum|bakar",
            "Na koliko stepeni Celzijusa voda ključa na nivou mora?|100",
            "Na koliko stepeni Celzijusa se voda ledi?|0",
            "Koja planeta je najbliža Suncu?|Merkur|Venera|Mars|Zemlja",
            "Koja je najveća planeta Sunčevog sistema?|Jupiter|Saturn|Neptun|Zemlja",
            "Koja planeta se zove „crvena planeta“?|Mars|Venera|Jupiter|Merkur",
            "Koja planeta je poznata po velikim prstenovima?|Saturn|Mars|Merkur|Venera",
            "Koliko planeta ima Sunčev sistem?|8",
            "Koja je treća planeta od Sunca?|Zemlja|Mars|Venera|Jupiter",
            "Kako se zove Zemljin prirodni satelit?|Mesec|Sunce|Fobos|Titan",
            "Za koliko dana Zemlja obiđe Sunce (otprilike)?|365",
            "Za koliko sati se Zemlja okrene oko svoje ose (otprilike)?|24",
            "Kako se zove naša galaksija?|Mlečni put|Andromeda|Orion|Veliki medved",
            "Šta je Sunce?|zvezda|planeta|kometa|satelit",
            "Koja je najviša planina na svetu?|Mont Everest|K2|Mon Blan|Kilimandžaro",
            "Koji je najveći okean?|Tihi okean|Atlantski okean|Indijski okean|Severni ledeni okean",
            "Koja je najveća vruća pustinja na svetu?|Sahara|Gobi|Kalahari|Atakama",
            "Kako se zove otopljena stena koja izlazi iz vulkana?|lava|led|pesak|bazalt",
            "Koje drvo daje žir?|hrast|bukva|lipa|jela",
            "Od koje biljke se pravi čokolada?|kakao|kafa|vanila|šećerna trska",
            "Koje voće je najpoznatiji izvor vitamina C?|pomorandža|banana|kruška|grožđe",
            "Koja biljka se okreće za suncem dok je mlada?|suncokret|ruža|lala|kukuruz",
            "Koja je najtvrđa prirodna materija?|dijamant|gvožđe|granit|kvarc",
            "Koliko stepeni ima pravi ugao?|90",
            "Koliki je zbir uglova u trouglu (u stepenima)?|180",
            "Koliko strana ima šestougao?|6",
            "Koliko strana ima osmougao?|8",
            "Koliko ivica ima kocka?|12",
            "Koliko temena ima kocka?|8",
            "Koliko strana ima kocka?|6",
            "Koji je najmanji prost broj?|2",
            "Koliko metara ima jedan kilometar?|1000",
            "Koliko je pi zaokruženo na dve decimale?|3,14|3,41|3,12|2,72",
    };

    static final String[] GDE_SE_NALAZI = {
            "U kom gradu se nalazi Ajfelov toranj?|Pariz|London|Rim|Brisel",
            "U kom gradu se nalazi Koloseum?|Rim|Atina|Milano|Napulj",
            "U kom gradu se nalazi Big Ben?|London|Pariz|Dablin|Edinburg",
            "U kom gradu se nalazi Kip slobode?|Njujork|Vašington|Čikago|Boston",
            "U kom gradu se nalazi Akropolj?|Atina|Rim|Solun|Istanbul",
            "U kom gradu se nalazi Sagrada Familija?|Barselona|Madrid|Sevilja|Valensija",
            "U kojoj državi se nalazi Tadž Mahal?|Indija|Pakistan|Iran|Egipat",
            "U kojoj državi se nalaze piramide u Gizi?|Egipat|Meksiko|Sudan|Maroko",
            "U kojoj državi se nalazi Veliki kineski zid?|Kina|Japan|Mongolija|Koreja",
            "U kojoj državi se nalazi Maču Pikču?|Peru|Meksiko|Čile|Kolumbija",
            "U kom gradu se nalazi Kosi toranj?|Piza|Firenca|Venecija|Rim",
            "U kom gradu se nalazi Brandenburška kapija?|Berlin|Beč|Minhen|Hamburg",
            "U kom gradu se nalazi Crveni trg?|Moskva|Sankt Peterburg|Kijev|Minsk",
            "U kojoj državi se nalazi čuvena Opera u Sidneju?|Australija|Novi Zeland|Kanada|Južna Afrika",
            "U kom gradu se nalazi kip Hrista Iskupitelja?|Rio de Žaneiro|Buenos Ajres|Lisabon|Lima",
            "U kom gradu se nalazi Burdž Kalifa, najviša zgrada na svetu?|Dubai|Doha|Rijad|Abu Dabi",
            "U kom gradu se nalazi Karlov most?|Prag|Budimpešta|Beč|Krakov",
            "U kom gradu se nalazi Ermitaž?|Sankt Peterburg|Moskva|Varšava|Riga",
            "U kom gradu se nalazi muzej Prado?|Madrid|Barselona|Lisabon|Rim",
            "U kojoj državi se nalazi Stounhendž?|Velika Britanija|Irska|Francuska|Norveška",
            "U kojoj državi se nalazi Alhambra?|Španija|Portugalija|Maroko|Italija",
            "U kojoj državi se nalazi dvorac Nojšvanštajn?|Nemačka|Austrija|Švajcarska|Francuska",
            "U kojoj državi se nalazi bazilika Svetog Petra?|Vatikan|Francuska|Malta|San Marino",
            "Na granici kojih država su Nijagarini vodopadi?|SAD i Kanade|SAD i Meksika|Brazila i Argentine|Kanade i Danske",
            "U kom gradu se nalazi Hram Svetog Save?|Beograd|Novi Sad|Niš|Kragujevac",
            "U kom gradu se nalazi Petrovaradinska tvrđava?|Novi Sad|Beograd|Smederevo|Subotica",
            "U kom gradu se nalazi Ćele kula?|Niš|Leskovac|Vranje|Kruševac",
            "U kom gradu se nalazi Kalemegdan?|Beograd|Novi Sad|Niš|Kragujevac",
            "Kod kog grada se nalazi Gamzigrad (Feliks Romulijana)?|Zaječar|Niš|Čačak|Valjevo",
            "Na kojoj reci se nalazi Golubačka tvrđava?|Dunav|Sava|Drina|Morava",
            "U kom gradu se nalazi Smederevska tvrđava?|Smederevo|Požarevac|Golubac|Pančevo",
            "U kojoj državi se nalazi Đavolja varoš?|Srbija|Crna Gora|Bosna i Hercegovina|Hrvatska",
            "U kojoj državi se nalaze Plitvička jezera?|Hrvatska|Slovenija|Bosna i Hercegovina|Srbija",
            "U kojoj državi se nalazi Kotor?|Crna Gora|Hrvatska|Albanija|Srbija",
            "U kojoj državi se nalazi Bled sa ostrvom na jezeru?|Slovenija|Austrija|Hrvatska|Italija",
            "U kom gradu se nalazi Stari most na Neretvi?|Mostar|Sarajevo|Višegrad|Banja Luka",
            "U kom gradu se nalazi most Mehmed-paše Sokolovića?|Višegrad|Mostar|Sarajevo|Zvornik",
            "U kom gradu se nalazi Dioklecijanova palata?|Split|Dubrovnik|Zadar|Rijeka",
            "Na kojoj planini se nalazi Avalski toranj?|Avala|Kosmaj|Fruška gora|Rudnik",
            "Na kojoj planini se nalazi Pančićev vrh?|Kopaonik|Zlatibor|Tara|Stara planina",
            "Kroz koji od ovih glavnih gradova protiče Dunav?|Beograd|Prag|Zagreb|Rim",
            "Na kojoj reci leži Pariz?|Sena|Rajna|Loara|Temza",
            "Na kojoj reci leži London?|Temza|Sena|Dunav|Rajna",
            "Na kojoj reci leži Rim?|Tibar|Po|Arno|Dunav",
            "Na kojoj reci leži Novi Sad?|Dunav|Sava|Tisa|Morava",
            "Na kojoj reci leži Niš?|Nišava|Ibar|Drina|Tisa",
            "Na kojoj reci leži Zagreb?|Sava|Drava|Dunav|Kupa",
            "Na kojoj reci leži Prag?|Vltava|Dunav|Laba|Odra",
            "Na ušću koje dve reke leži Beograd?|Save i Dunava|Drine i Save|Morave i Dunava|Tise i Dunava",
            "Koja reka čini veći deo granice između Srbije i Bosne i Hercegovine?|Drina|Sava|Una|Morava",
            "Koja je najduža reka u Evropi?|Volga|Dunav|Rajna|Dnjepar",
            "Na kom kontinentu je pustinja Sahara?|Afrika|Azija|Australija|Južna Amerika",
            "Na kom kontinentu je reka Amazon?|Južna Amerika|Afrika|Azija|Severna Amerika",
            "Na kom kontinentu su planine Himalaji?|Azija|Evropa|Afrika|Južna Amerika",
            "Na kom kontinentu su Ande?|Južna Amerika|Severna Amerika|Azija|Afrika",
            "Gde se nalazi Mrtvo more?|na Bliskom istoku|u Africi|u južnoj Americi|u Skandinaviji",
            "Koje more je između Italije i Balkana?|Jadransko more|Crno more|Egejsko more|Baltičko more",
            "Koje more zapljuskuje Rumuniju i Bugarsku?|Crno more|Jadransko more|Egejsko more|Severno more",
            "U kom moru je ostrvo Krit?|Sredozemnom moru|Crnom moru|Severnom moru|Baltičkom moru",
            "Koji okean je između Evrope i Severne Amerike?|Atlantski|Tihi|Indijski|Južni",
            "Na kom ostrvu je Havana?|Kuba|Jamajka|Haiti|Portoriko",
            "Koja je najveća država na svetu po površini?|Rusija|Kanada|Kina|SAD",
            "Koja država ima najviše stanovnika na svetu?|Indija|Kina|SAD|Indonezija",
            "Koja je najmanja država na svetu?|Vatikan|Monako|San Marino|Malta",
            "Koja država ima oblik čizme?|Italija|Grčka|Čile|Norveška",
            "Koliko saveznih država imaju SAD?|50",
            "Kroz koliko država protiče Dunav?|10",
            "Koja država se zove i „zemlja izlazećeg sunca“?|Japan|Kina|Koreja|Tajland",
            "Koja država se zove i „zemlja hiljadu jezera“?|Finska|Švedska|Kanada|Norveška",
    };

    static final String[] SRBIJA = {
            "Koji je glavni grad Vojvodine?|Novi Sad|Subotica|Zrenjanin|Pančevo",
            "Koji grad se naziva „srpska Atina“?|Novi Sad|Beograd|Kragujevac|Sremski Karlovci",
            "U kom selu je rođen Nikola Tesla?|Smiljan|Idvor|Mokrin|Ivanjica",
            "U kom selu je rođen Mihajlo Pupin?|Idvor|Smiljan|Tršić|Orašac",
            "U kom selu je rođen Vuk Stefanović Karadžić?|Tršić|Idvor|Smiljan|Orašac",
            "U kom selu je podignut Prvi srpski ustanak?|Orašac|Takovo|Tršić|Topola",
            "Ko je bio vođa Prvog srpskog ustanka?|Karađorđe|Miloš Obrenović|Hajduk Veljko|knez Lazar",
            "Ko je predvodio Drugi srpski ustanak?|Miloš Obrenović|Karađorđe|Stevan Sinđelić|Hajduk Veljko",
            "Koje godine je počeo Prvi srpski ustanak?|1804",
            "Koje godine je bila Kosovska bitka?|1389",
            "Ko je predvodio srpsku vojsku u Kosovskoj bici?|knez Lazar|car Dušan|Stefan Nemanja|kralj Milutin",
            "Ko je bio prvi srpski arhiepiskop?|Sveti Sava|Stefan Prvovenčani|Stefan Nemanja|Sveti Simeon",
            "Koji srpski vladar je doneo Zakonik 1349. godine?|car Dušan|knez Lazar|kralj Milutin|despot Stefan",
            "Ko je osnivač dinastije Nemanjića?|Stefan Nemanja|Sveti Sava|car Dušan|kralj Milutin",
            "Ko je bio komandant u bici na Čegru?|Stevan Sinđelić|Karađorđe|Hajduk Veljko|Janko Katić",
            "Kada se slavi Savindan?|27. januara|6. maja|28. juna|14. januara",
            "Kada je Vidovdan?|28. juna|6. maja|27. januara|19. avgusta",
            "Kada je Đurđevdan?|6. maja|28. juna|19. decembra|27. januara",
            "Kada pravoslavni vernici u Srbiji slave Božić?|7. januara|25. decembra|1. januara|14. januara",
            "Kako se zove srpski narodni instrument sa jednom žicom?|gusle|frula|tamburica|gajde",
            "Koja je valuta u Srbiji?|dinar|evro|marka|forinta",
            "Koliko slova ima srpska azbuka?|30",
            "Koje slovo dolazi posle slova G u azbuci?|D|H|Đ|E",
            "Koje je poslednje slovo azbuke?|Š|Ž|Z|Ć",
            "Koje boje su na zastavi Srbije, odozgo nadole?|crvena, plava, bela|plava, bela, crvena|bela, plava, crvena|crvena, bela, plava",
            "Kako se zove himna Srbije?|Bože pravde|Hej, Sloveni|Tamo daleko|Marš na Drinu",
            "Koja planina je poznata po misterioznoj piramidi kod Sokobanje?|Rtanj|Kopaonik|Tara|Zlatibor",
            "Koji nacionalni park je kanjon Dunava u Srbiji?|Đerdap|Tara|Kopaonik|Fruška gora",
            "Na kojoj planini su brojni fruškogorski manastiri?|Fruška gora|Tara|Zlatibor|Rudnik",
            "Koje je najveće veštačko jezero u Srbiji?|Đerdapsko jezero|Vlasinsko jezero|Palićko jezero|Srebrno jezero",
            "Pored kog grada se nalazi Palićko jezero?|Subotica|Sombor|Kikinda|Novi Sad",
            "Pored kog grada se nalazi Srebrno jezero?|Veliko Gradište|Kladovo|Golubac|Smederevo",
            "U kom mestu se održava Sabor trubača?|Guča|Čačak|Užice|Kraljevo",
            "U kom gradu se održava muzički festival Egzit?|Novi Sad|Beograd|Niš|Subotica",
            "Koji grad je poznat po „Nišvilu“?|Niš|Kragujevac|Novi Sad|Pirot",
            "Po čemu je poznat Pirot?|po ćilimima|po trubačima|po kristalu|po svili",
            "Koji grad je poznat po Zastavinoj fabrici automobila?|Kragujevac|Kraljevo|Čačak|Kruševac",
            "Gde se nalazi Šarganska osmica?|na Mokroj Gori|na Kopaoniku|u Sremu|na Fruškoj gori",
            "Koja srpska teniserka je osvojila Rolan Garos 2008. godine?|Ana Ivanović|Jelena Janković|Monika Seleš|Jelena Dokić",
            "Ko je osvojio najviše grend slem titula u muškom tenisu?|Novak Đoković|Rafael Nadal|Rodžer Federer|Pit Sampras",
            "Koji košarkaš iz Sombora je proglašen za najboljeg igrača NBA lige?|Nikola Jokić|Vlade Divac|Peđa Stojaković|Bogdan Bogdanović",
            "U kom gradu je rođen Novak Đoković?|Beograd|Novi Sad|Niš|Kraljevo",
            "Koji fudbalski klub je 1991. osvojio Kup šampiona?|Crvena zvezda|Partizan|Vojvodina|Hajduk",
    };

    static final String[] SPORT = {
            "Koliko igrača ima jedan fudbalski tim na terenu?|11",
            "Koliko igrača ima jedan košarkaški tim na terenu?|5",
            "Koliko igrača ima jedan odbojkaški tim na terenu?|6",
            "Koliko igrača, sa golmanom, ima vaterpolo tim u vodi?|7",
            "Koliko igrača, sa golmanom, ima rukometni tim na terenu?|7",
            "Koliko minuta traje jedno poluvreme fudbalske utakmice?|45",
            "Koliko minuta traje jedna četvrtina u FIBA košarci?|10",
            "Koliko poena vredi koš iz slobodnog bacanja?|1",
            "Na kojoj podlozi se igra Vimbldon?|trava|šljaka|beton|tepih",
            "Na kojoj podlozi se igra Rolan Garos?|šljaka|trava|beton|tepih",
            "Koliko grend slem turnira ima u teniskoj sezoni?|4",
            "Gde su održane prve moderne Olimpijske igre 1896. godine?|Atina|Pariz|London|Rim",
            "Koliko krugova ima na olimpijskoj zastavi?|5",
            "Na koliko godina se održavaju Letnje olimpijske igre?|4",
            "Koliko polja ima šahovska tabla?|64",
            "Koja šahovska figura se kreće u obliku slova L?|skakač (konj)|lovac|top|kraljica",
            "Kako se zove potez u šahu kad kralj i top zamene mesta?|rokada|šah-mat|pat|gambit",
            "Koliko kilometara je dugačak maraton (zaokruženo)?|42|40|21|50",
            "Koja zemlja je osvojila najviše Svetskih prvenstava u fudbalu?|Brazil|Nemačka|Italija|Argentina",
            "Koliko rupa ima standardni teren za golf?|18",
            "Koliko poena vredi tačdaun u američkom fudbalu?|6",
            "Kako se zove pogodak sa tri gola jednog igrača u istoj utakmici?|het-trik|ofsajd|penal|korner",
            "U kom sportu se koristi pak?|hokej na ledu|kriket|badminton|polo",
            "U kom sportu se koristi loptica sa perjem?|badminton|tenis|stoni tenis|skvoš",
            "Koja boja majice označava lidera na Tur de Fransu?|žuta|roze|zelena|bela",
            "Koliko traje jedna runda u profesionalnom boksu (minuta)?|3",
            "Koliko je dugačak bazen za olimpijsko plivanje (metara)?|50",
            "Koliko metara je visok košarkaški obruč?|3,05|2,75|3,50|2,95",
    };

    static final String[] JEZIK = {
            "Kako glasi množina reči „čovek“?|ljudi|čoveci|čovekovi|čovečani",
            "Kako glasi množina reči „dete“?|deca|deti|detići|detovi",
            "Kako glasi množina reči „oko“?|oči|oka|okovi|oćevi",
            "Kako glasi množina reči „uho“?|uši|uha|uhovi|ušovi",
            "Koja reč znači isto što i „hrabar“?|smeo|plašljiv|lenj|tih",
            "Koja reč znači isto što i „brz“?|hitar|spor|težak|tih",
            "Koja reč je suprotna od „vredan“?|lenj|marljiv|pametan|veseo",
            "Koja reč je suprotna od „širok“?|uzak|dug|visok|debeo",
            "Koja reč je suprotna od „mudar“?|glup|pametan|star|tih",
            "Šta znači izraz „pala mu je sekira u med“?|imao je sreće|povredio se|izgubio je posao|pokvario je nešto",
            "Šta znači izraz „gledati kroz prste“?|praštati nešto|loše videti|krasti|igrati se",
            "Šta znači izraz „obesiti o klin“?|prestati sa nečim|okačiti kaput|sakriti nešto|kazniti nekoga",
            "Šta znači izraz „baciti pušku u šaš“?|odustati|ići u lov|sakriti se|pobediti",
            "Šta znači izraz „ni luk jeo, ni luk mirisao“?|praviti se nevešt|ne voleti luk|biti gladan|biti umoran",
            "Šta znači izraz „kupiti mačka u džaku“?|kupiti nešto neprovereno|kupiti ljubimca|uštedeti novac|prevariti nekoga",
            "Kako se završava poslovica „Ko rano rani…“?|dve sreće grabi|taj kasno legne|dobro spava|ostaje gladan",
            "Kako se završava poslovica „Bez muke…“?|nema nauke|nema hleba|nema sreće|nema druga",
            "Kako se završava poslovica „Ko drugome jamu kopa…“?|sam u nju pada|lopatu nosi|dobro radi|ne spava",
            "Kako se završava poslovica „Ne pada sneg da pokrije breg, nego…“?|da svaka zverka pokaže svoj trag|da deca imaju sanke|da bude zima|da se sakrije trava",
            "Kako se završava poslovica „Ispeci, pa…“?|reci|pojedi|podeli|ćuti",
            "Kako se završava poslovica „Gde ima dima…“?|ima i vatre|ima i kiše|nema vazduha|ima i ljudi",
            "Kako se završava poslovica „Sto ljudi…“?|sto ćudi|sto puta|sto kuća|sto želja",
            "Koliko slogova ima reč „pomorandža“?|4",
            "Koliko slogova ima reč „telefon“?|3",
            "Koliko slova ima reč „džemper“ napisana ćirilicom?|6",
            "Koja od ovih reči je napisana pravilno?|uopšte|uobšte|u opšte|uopšťe",
            "Koja od ovih reči je napisana pravilno?|odjednom|od jednom|odjedno|otjednom",
            "Koja od ovih reči je napisana pravilno?|podsetnik|potsetnik|pod setnik|podssetnik",
            "Koja od ovih reči je napisana pravilno?|predsednik|pretsednik|presednik|predsjednik",
            "Kako se kaže „hello“ na srpskom?|zdravo|hvala|izvini|doviđenja",
            "Šta znači engleska reč „window“?|prozor|vrata|zid|krov",
            "Šta znači engleska reč „library“?|biblioteka|laboratorija|knjižara i kafić|škola",
            "Šta znači nemačka reč „Danke“?|hvala|zdravo|molim|izvini",
            "Šta znači italijanska reč „ciao“?|zdravo ili ćao|hvala|molim|laku noć",
            "Šta znači španska reč „gracias“?|hvala|zdravo|dobro jutro|prijatno",
            "Šta znači francuska reč „bonjour“?|dobar dan|laku noć|hvala|doviđenja",
    };

    static final String[] VALUTE = {
            "Koja je valuta u Japanu?|jen|juan|von|rupija",
            "Koja je valuta u Velikoj Britaniji?|funta|evro|dolar|kruna",
            "Koja je valuta u SAD?|dolar|funta|evro|peso",
            "Koja je valuta u Švajcarskoj?|franak|evro|kruna|marka",
            "Koja je valuta u Rusiji?|rublja|grivna|zlot|lev",
            "Koja je valuta u Kini?|juan|jen|von|rupija",
            "Koja je valuta u Indiji?|rupija|juan|dinar|taka",
            "Koja je valuta u Bosni i Hercegovini?|konvertibilna marka|dinar|evro|kuna",
            "Koja je valuta u Mađarskoj?|forinta|evro|kruna|lej",
            "Koja je valuta u Hrvatskoj?|evro|kuna|dinar|marka",
            "Koja je valuta u Poljskoj?|zlot|forinta|kruna|evro",
            "Koja je valuta u Češkoj?|kruna|zlot|evro|forinta",
            "Koja je valuta u Turskoj?|lira|dinar|drahma|rial",
            "Koja je valuta u Rumuniji?|lej|lev|forinta|evro",
            "Koja je valuta u Severnoj Makedoniji?|denar|dinar|evro|lek",
            "Koja je valuta u Meksiku?|peso|dolar|real|sol",
            "Koja je valuta u Brazilu?|real|peso|dolar|eskudo",
            "Koja je valuta u Ukrajini?|grivna|rublja|zlot|lej",
            "Koja je valuta u Švedskoj?|kruna|evro|funta|franak",
            "Koja je valuta u Crnoj Gori?|evro|dinar|marka|lek",
    };

    static final String[] JAVA = {
            // Java jezik
            "Koja je podrazumevana vrednost polja tipa int u Java klasi?|0|null|-1|nedefinisana",
            "Šta poredi operator == kada su u pitanju objekti?|da li su reference iste|da li su vrednosti iste|hash kodove objekata|nazive klasa",
            "Koju metodu treba prepisati uvek kad se prepiše equals()?|hashCode()|toString()|compareTo()|clone()",
            "Koja od ovih klasa je nepromenljiva (immutable)?|String|StringBuilder|ArrayList|HashMap",
            "Koliko bita ima tip int u Javi?|32",
            "Koliko bita ima tip long u Javi?|64",
            "Koliko bajtova zauzima tip char u Javi?|2",
            "Šta znači final kod lokalne promenljive?|vrednost joj se ne može ponovo dodeliti|promenljiva postaje statička|nije vidljiva van metode|objekat na koji pokazuje ne može da se menja",
            "Šta znači final kod klase?|klasa ne može da se nasleđuje|klasa ne može da ima instance|sve metode su statičke|klasa je apstraktna",
            "Može li apstraktna klasa da ima konstruktor?|da|ne|samo privatni|samo ako nema apstraktnih metoda",
            "Koliko klasa jedna Java klasa može direktno da nasledi preko extends?|1",
            "Koja ključna reč se koristi kada klasa ostvaruje interfejs?|implements|extends|inherits|uses",
            "Od koje verzije Jave interfejsi mogu da imaju default metode?|Java 8|Java 5|Java 11|Java 17",
            "U kojoj verziji Jave su record klase postale stalni deo jezika?|Java 16|Java 8|Java 11|Java 21",
            "U kojoj verziji Jave je uvedena reč var za lokalne promenljive?|Java 10|Java 8|Java 11|Java 14",
            "U kojoj verziji Jave su virtuelne niti (virtual threads) postale stalni deo jezika?|Java 21|Java 17|Java 19|Java 11",
            "U kojoj verziji Jave su sealed klase postale stalni deo jezika?|Java 17|Java 11|Java 15|Java 21",
            "Šta je checked izuzetak?|izuzetak koji mora da se uhvati ili navede u throws|svaki RuntimeException|greška JVM-a kao OutOfMemoryError|izuzetak koji kompajler ignoriše",
            "Koji od ovih izuzetaka je unchecked?|NullPointerException|IOException|SQLException|ClassNotFoundException",
            "Da li se finally blok izvrši ako try blok sadrži return?|da, finally se ipak izvrši|ne, preskače se|samo ako je bačen izuzetak|kompajler to ne dozvoljava",
            "Čemu služi try-with-resources?|automatski zatvara resurse kad se blok završi|hvata sve izuzetke|ponavlja blok dok ne uspe|pokreće kod u novoj niti",
            "Koji interfejs mora da ima objekat da bi išao u try-with-resources?|AutoCloseable|Serializable|Runnable|Iterable",
            "Šta je autoboxing?|automatsko pretvaranje int u Integer i slično|pakovanje aplikacije u JAR|automatsko kastovanje long u int|serijalizacija objekta",
            "Šta daje Integer.valueOf(127) == Integer.valueOf(127)?|true|false|baca izuzetak|ne kompajlira se",
            "Gde JVM čuva objekte napravljene sa new?|na hipu (heap)|na steku|u registrima procesora|u class fajlu",
            "Šta radi garbage collector?|oslobađa memoriju objekata na koje više niko ne pokazuje|briše neiskorišćen kod|kompajlira bajtkod|zatvara konekcije ka bazi",
            "Šta javac pravi od .java fajla?|bajtkod u .class fajlu|mašinski kod za procesor|JAR arhivu|.exe fajl",
            "Šta radi JIT kompajler?|prevodi bajtkod u mašinski kod dok program radi|proverava stil koda|pakuje biblioteke|pokreće testove",
            "Kako Java prosleđuje argumente metodama?|uvek po vrednosti, kod objekata se kopira referenca|uvek po referenci|primitivne po referenci, objekte po vrednosti|zavisi od modifikatora",
            "Šta znači static kod metode?|pripada klasi, a ne objektu|ne može da vrati vrednost|ne može da se pozove spolja|izvršava se samo jednom",
            "Koja vidljivost važi kad se ne napiše nijedan modifikator pristupa?|samo unutar istog paketa|samo unutar klase|svuda|samo u podklasama",
            "Šta je overloading?|više metoda istog imena sa različitim parametrima|nova implementacija nasleđene metode|nasleđivanje više klasa|skrivanje polja",
            "Šta je overriding?|nova implementacija nasleđene metode u podklasi|više metoda istog imena sa različitim parametrima|poziv konstruktora roditelja|kopiranje objekta",
            "Koja anotacija označava da metoda prepisuje nasleđenu?|@Override|@Overload|@Inherited|@Super",
            "Koja klasa je najbolja za spajanje mnogo stringova u petlji?|StringBuilder|String|Character|StringTokenizer",
            "Koja je razlika između StringBuffer i StringBuilder?|StringBuffer je sinhronizovan, StringBuilder nije|StringBuilder je nepromenljiv|StringBuffer je uvek brži|nema razlike",
            "Šta proverava instanceof?|da li je objekat date klase ili interfejsa|da li su dva objekta jednaka|da li je promenljiva inicijalizovana|da li klasa postoji",
            "Šta vraća \"java\".length()?|4",
            // Kolekcije
            "Koja kolekcija ne dozvoljava duplikate?|Set|List|Queue|ArrayList",
            "Kolika je složenost get(i) kod ArrayList?|O(1)|O(n)|O(log n)|O(n²)",
            "Kolika je prosečna složenost get(ključ) kod HashMap?|O(1)|O(n)|O(log n)|O(n²)",
            "Kolika je složenost get(ključ) kod TreeMap?|O(log n)|O(1)|O(n)|O(n²)",
            "Koja mapa čuva ključeve sortirane?|TreeMap|HashMap|LinkedHashMap|Hashtable",
            "Koja mapa čuva redosled ubacivanja?|LinkedHashMap|HashMap|TreeMap|Hashtable",
            "Da li HashMap dozvoljava null ključ?|da, jedan|ne|da, više njih|samo u starim verzijama",
            "Šta se obično desi kad se iz ArrayList briše unutar for-each petlje?|ConcurrentModificationException|ništa, radi normalno|petlja počne ispočetka|lista se sama kopira",
            "Koja mapa je bezbedna za više niti i pri tom brza?|ConcurrentHashMap|HashMap|TreeMap|LinkedHashMap",
            "Šta vraća List.of(1, 2, 3)?|nepromenljivu listu|ArrayList koja može da se menja|LinkedList|niz int[]",
            "Koji interfejs koristi TreeSet da uporedi elemente kad nema Comparator?|Comparable|Iterable|Cloneable|Serializable",
            "Koja struktura radi po principu LIFO (poslednji ušao, prvi izašao)?|stek|red (queue)|HashSet|TreeMap",
            "Koji element PriorityQueue podrazumevano vraća prvi?|najmanji|najveći|prvi ubačeni|nasumičan",
            "Koliki je početni kapacitet HashMap po podrazumevanju?|16",
            "Koliki je podrazumevani load factor kod HashMap?|0.75|0.5|1.0|0.9",
            // Lambda i stream
            "Šta je funkcionalni interfejs?|interfejs sa tačno jednom apstraktnom metodom|interfejs bez metoda|interfejs sa samo default metodama|klasa sa jednom metodom",
            "Koja operacija nad stream-om je terminalna?|collect|map|filter|sorted",
            "Koja operacija nad stream-om je intermedijarna (lenja)?|map|forEach|collect|count",
            "Čemu služi Optional?|predstavlja vrednost koja možda ne postoji|ubrzava stream-ove|čuva više vrednosti|pravi kopiju objekta",
            "Koji funkcionalni interfejs prima argument i vraća boolean?|Predicate|Supplier|Consumer|Runnable",
            "Koji funkcionalni interfejs ne prima ništa, a vraća vrednost?|Supplier|Consumer|Function|Predicate",
            "Koji funkcionalni interfejs prima argument i ništa ne vraća?|Consumer|Supplier|Function|Predicate",
            "Šta radi flatMap nad stream-om?|spaja ugnežđene stream-ove u jedan|filtrira elemente|sortira elemente|broji elemente",
            "Da li stream može da se iskoristi dva puta?|ne, posle terminalne operacije je potrošen|da, uvek|samo paralelni|samo sortirani",
            // Niti
            "Šta garantuje volatile?|da promene vide sve niti|da je i++ atomično|zaključavanje objekta|brže izvršavanje",
            "Da li je count++ atomična operacija u Javi?|ne|da|samo za int|samo za volatile polje",
            "Koja klasa daje atomično povećanje brojača bez synchronized?|AtomicInteger|Integer|ThreadLocal|Thread",
            "Šta je deadlock?|niti zauvek čekaju jedna drugu|nit koja troši sav procesor|izuzetak u niti|nit koja je završila rad",
            "Šta obezbeđuje synchronized blok?|samo jedna nit u isto vreme ulazi u blok nad istim objektom|blok se pokreće u novoj niti|kod radi brže|klasa ne može da se nasledi",
            "Koja je razlika između Runnable i Callable?|Callable vraća rezultat i može da baci checked izuzetak|Runnable vraća rezultat|Callable radi samo u glavnoj niti|nema razlike",
            "Šta vraća ExecutorService.submit()?|Future|Thread|void|Runnable",
            "Šta je CompletableFuture?|asinhroni rezultat na koji se mogu nadovezivati koraci|vrsta zaključavanja|kolekcija za niti|deo garbage collector-a",
            "Šta radi ThreadLocal?|svaka nit ima svoju kopiju vrednosti|deli vrednost među nitima|zaključava nit|meri vreme niti",
            "Koja metoda zaista pokreće novu nit?|start()|run()|execute()|begin()",
            // Spring
            "Šta je dependency injection?|objekat dobija zavisnosti spolja umesto da ih sam pravi|nasleđivanje klasa|ubacivanje SQL-a u upit|učitavanje JAR fajlova",
            "Koja anotacija označava REST kontroler u Springu?|@RestController|@Service|@Repository|@Entity",
            "@RestController je isto što i?|@Controller i @ResponseBody|@Component i @Service|@Controller i @RequestBody|@Configuration i @Bean",
            "Koji je podrazumevani scope Spring bean-a?|singleton|prototype|request|session",
            "Koja anotacija čita {id} iz putanje /users/{id}?|@PathVariable|@RequestParam|@RequestBody|@RequestHeader",
            "Koja anotacija čita ?page=2 iz adrese?|@RequestParam|@PathVariable|@RequestBody|@RequestHeader",
            "Koja anotacija pretvara JSON telo zahteva u objekat?|@RequestBody|@ResponseBody|@PathVariable|@RequestParam",
            "Koji način ubacivanja zavisnosti Spring preporučuje?|kroz konstruktor|kroz polje sa @Autowired|kroz statičko polje|ručno sa new",
            "Šta radi @Transactional?|metoda radi u transakciji, a greška poništava izmene|kešira rezultat metode|pokreće metodu asinhrono|beleži logove",
            "Na koje izuzetke @Transactional podrazumevano radi rollback?|RuntimeException i Error|na svaki izuzetak|samo na checked izuzetke|ni na jedan",
            "Zašto @Transactional ne radi kad metoda pozove drugu metodu iste klase?|poziv ne prolazi kroz Spring proxy|transakcije rade samo u kontrolerima|metoda mora da bude statička|zato što je bean singleton",
            "Šta je Spring Boot starter?|paket zavisnosti za jednu oblast, npr. web ili JPA|komanda za pokretanje|vrsta bean-a|anotacija za testove",
            "Koji server Spring Boot web aplikacija podrazumevano koristi?|Tomcat|Jetty|Undertow|Netty",
            "Na kom portu se Spring Boot aplikacija podrazumevano pokreće?|8080",
            "Šta obuhvata @SpringBootApplication?|@Configuration, @EnableAutoConfiguration i @ComponentScan|@RestController i @Service|@Entity i @Repository|@Test i @Bean",
            "Koja anotacija stoji na metodi koja vraća bean u @Configuration klasi?|@Bean|@Component|@Autowired|@Value",
            "Šta radi @Value(\"${app.name}\")?|ubacuje vrednost iz podešavanja aplikacije|pravi novi bean|proverava polje|pravi konstantu",
            "Čemu služi @Profile u Springu?|uključuje bean-ove samo za određeno okruženje, npr. dev ili prod|pravi korisnički nalog|podešava logovanje|daje bezbednosnu ulogu",
            "Koja anotacija na klasi pravi zajedničko hvatanje izuzetaka za sve kontrolere?|@ControllerAdvice|@ResponseStatus|@Aspect|@Component",
            "Kako se u Spring Security čuvaju lozinke?|heširane, npr. BCrypt-om|kao običan tekst|kodirane Base64|u kolačiću",
            "Šta je Spring Data JPA repository?|interfejs za koji Spring sam pravi implementaciju|klasa za HTTP pozive|tabela u bazi|keš",
            "Šta Spring Data pravi od imena metode findByEmail?|upit koji traži po koloni email|novu tabelu|REST rutu|indeks",
            // JPA i Hibernate
            "Koja anotacija označava JPA entitet?|@Entity|@Column|@Id|@Repository",
            "Koja anotacija označava primarni ključ entiteta?|@Id|@Key|@Primary|@Column",
            "Šta je N+1 problem?|jedan upit za listu, pa još po jedan za svaki element|upit vraća jedan red viška|N+1 otvorenih konekcija|greška u brojanju redova",
            "Kako se najčešće rešava N+1 problem?|JOIN FETCH ili entity graph|dodavanjem indeksa|većim brojem konekcija|ponovnim pokretanjem servera",
            "Koji je podrazumevani fetch za @ManyToOne?|EAGER|LAZY|NONE|BATCH",
            "Koji je podrazumevani fetch za @OneToMany?|LAZY|EAGER|NONE|JOIN",
            "Kada nastaje LazyInitializationException?|kad se lenja veza čita posle zatvaranja sesije|kad SQL ima grešku|kad se ponovi ključ|kad pukne konekcija",
            "Šta označava mappedBy u vezi između entiteta?|stranu veze koja nije vlasnik stranog ključa|ime tabele|ime kolone|redosled sortiranja",
            "Šta je dirty checking u Hibernate-u?|automatsko snimanje izmenjenih entiteta pri commit-u|provera loših podataka u bazi|provera unosa korisnika|čišćenje keša",
            "Kojom anotacijom se u JPA radi optimističko zaključavanje?|@Version|@Lock|@Transactional|@Id",
            // SQL i baze
            "Koja SQL klauzula filtrira grupe posle GROUP BY?|HAVING|WHERE|ORDER BY|LIMIT",
            "Koji JOIN vraća sve redove leve tabele i poklapanja iz desne?|LEFT JOIN|INNER JOIN|RIGHT JOIN|CROSS JOIN",
            "Koji JOIN vraća samo redove koji se poklapaju u obe tabele?|INNER JOIN|LEFT JOIN|FULL JOIN|CROSS JOIN",
            "Šta znači A u ACID?|atomičnost|dostupnost|autentifikacija|asinhronost",
            "Šta znači I u ACID?|izolacija|integritet|indeksiranje|inkrementalnost",
            "Čemu služi indeks u bazi?|ubrzava pretragu po koloni|šifruje podatke|pravi rezervnu kopiju|briše duplikate",
            "Šta parametrizovani upit (PreparedStatement) sprečava?|SQL injection|deadlock|N+1 problem|curenje memorije",
            "Koji je najstroži nivo izolacije transakcija u SQL standardu?|SERIALIZABLE|READ COMMITTED|REPEATABLE READ|READ UNCOMMITTED",
            "Šta je dirty read?|čitanje izmena druge transakcije koje još nisu potvrđene|čitanje obrisanih redova|čitanje bez indeksa|čitanje iz keša",
            "Šta je strani ključ?|kolona koja pokazuje na primarni ključ druge tabele|ključ za šifrovanje|svaki jedinstveni indeks|kolona koja ne sme biti prazna",
            "Po čemu se COUNT(kolona) razlikuje od COUNT(*)?|COUNT(kolona) ne broji NULL vrednosti|COUNT(*) ne broji NULL vrednosti|nema razlike|COUNT(kolona) broji duplikate dvaput",
            "Šta je normalizacija baze?|uklanjanje ponavljanja podataka deljenjem na tabele|pravljenje indeksa|šifrovanje tabela|pravljenje rezervne kopije",
            "Koja SQL naredba menja postojeće redove?|UPDATE|INSERT|ALTER|SELECT",
            "Koja SQL naredba menja strukturu tabele?|ALTER TABLE|UPDATE|INSERT|MODIFY ROW",
            // REST i HTTP
            "Koji HTTP metod je idempotentan?|PUT|POST|PATCH|CONNECT",
            "Koji HTTP metod je bezbedan, odnosno ne menja stanje?|GET|POST|DELETE|PUT",
            "Koji HTTP status znači da je resurs uspešno napravljen?|201",
            "Koji HTTP status znači da resurs nije pronađen?|404",
            "Koji HTTP status znači da korisnik nije prijavljen (neautentifikovan)?|401",
            "Koji HTTP status znači da je korisnik prijavljen, ali nema pravo pristupa?|403",
            "Koji HTTP status znači uspeh bez tela odgovora?|204",
            "Koji HTTP status znači previše zahteva (rate limit)?|429",
            "Koji HTTP status znači sukob sa trenutnim stanjem resursa?|409",
            "Koji HTTP status znači unutrašnju grešku servera?|500",
            "Šta znači da je REST stateless?|svaki zahtev nosi sve što treba, server ne pamti sesiju|server ne čuva ništa u bazi|odgovor nema status|nema prijave korisnika",
            "Šta je JWT?|potpisan token sa podacima o korisniku|vrsta baze|Java web server|format logova",
            "U kom zaglavlju se obično šalje JWT?|Authorization: Bearer|Content-Type|Accept|User-Agent",
            "Čemu služi CORS?|određuje kojim drugim domenima browser dozvoljava da zovu API|šifruje saobraćaj|kešira odgovore|deli opterećenje",
            // Testiranje
            "Koja anotacija označava test metodu u JUnit 5?|@Test|@Case|@Check|@Run",
            "Koja anotacija u JUnit 5 pokreće metodu pre svakog testa?|@BeforeEach|@BeforeAll|@Setup|@Init",
            "Čemu služi Mockito?|pravi lažne (mock) zavisnosti za testove|meri pokrivenost koda|pokreće bazu|piše dokumentaciju",
            "Koja Spring Boot anotacija podiže ceo kontekst aplikacije za test?|@SpringBootTest|@WebMvcTest|@DataJpaTest|@JsonTest",
            "Koja Spring Boot anotacija testira samo web sloj (kontrolere)?|@WebMvcTest|@SpringBootTest|@DataJpaTest|@JsonTest",
            "Šta radi Testcontainers?|pokreće pravu bazu ili servis u Docker-u za vreme testa|kešira testove|pravi mock objekte|je CI server",
            // Paterni i arhitektura
            "Koji patern obezbeđuje samo jednu instancu klase?|Singleton|Factory|Observer|Adapter",
            "Koji patern pravi složen objekat korak po korak?|Builder|Singleton|Proxy|Strategy",
            "Koji patern menja algoritam u toku rada preko zajedničkog interfejsa?|Strategy|Builder|Singleton|Facade",
            "Koji patern obaveštava pretplatnike kad se nešto promeni?|Observer|Decorator|Factory|Composite",
            "Koji patern prilagođava jedan interfejs drugom?|Adapter|Observer|Builder|Prototype",
            "Koji patern dodaje ponašanje tako što omota objekat?|Decorator|Singleton|Factory|Iterator",
            "Na kom paternu počivaju Spring AOP i @Transactional?|Proxy|Builder|Observer|Prototype",
            "Šta znači S u SOLID?|svaka klasa ima jednu odgovornost|sve metode su statičke|sigurnost pre svega|singleton svuda",
            "Šta znači D u SOLID?|zavisi od apstrakcija, a ne od konkretnih klasa|dokumentuj sve|dupliraj kod radi brzine|deli bazu između servisa",
            "Šta znači L u SOLID?|podtip mora moći da zameni nadtip|lenje učitavanje|lokalne promenljive|labavo testiranje",
            "Šta je DTO?|objekat za prenos podataka između slojeva|tabela u bazi|vrsta testa|bezbednosni token",
            "Šta radi circuit breaker u mikroservisima?|privremeno prekida pozive ka servisu koji ne radi|šifruje komunikaciju|deli opterećenje|beleži logove",
            "Šta znači da je API poziv idempotentan?|ponovljen poziv ima isti efekat kao jedan|poziv je uvek brz|poziv nema parametre|poziv uvek vraća 200",
            // Alati
            "Koji fajl opisuje Maven projekat?|pom.xml|build.gradle|package.json|settings.gradle",
            "Koji Maven scope važi samo za testove?|test|provided|runtime|compile",
            "Koja Maven komanda pravi JAR i usput pokreće testove?|mvn package|mvn clean|mvn validate|mvn site",
    };

    /** Priprema za Claude Certified Architect – Foundations: agenti, Claude Code, promptovi, alati i MCP, kontekst. */
    static final String[] CLAUDE = {
            // Agenti i orkestracija
            "Koji stop_reason znači da Claude želi da pozove alat?|tool_use|end_turn|max_tokens|stop_sequence",
            "Koji stop_reason znači da je Claude prirodno završio odgovor?|end_turn|tool_use|max_tokens|pause_turn",
            "Koji stop_reason znači da je odgovor presečen zbog limita tokena?|max_tokens|end_turn|tool_use|refusal",
            "Kada se agentska petlja završava?|kad stop_reason više nije tool_use, npr. end_turn|posle tačno tri poziva|kad odgovor sadrži reč „gotovo“|kad nestane interneta",
            "Kako se rezultat alata vraća Claude-u?|kao tool_result blok u user poruci|kao nova system poruka|kao assistant poruka|kroz HTTP zaglavlje",
            "Šta povezuje tool_result sa pozivom alata na koji odgovara?|tool_use_id|naziv modela|temperatura|broj tokena",
            "Koje polje u tool_result označava da je alat pao?|is_error|error_code|failed|status",
            "Alat vrati grešku usred zadatka. Šta je najbolje?|vratiti grešku Claude-u u tool_result da se prilagodi|prekinuti ceo zadatak|prećutati grešku|izmisliti rezultat",
            "Da li subagent automatski dobija istoriju razgovora koordinatora?|ne, potreban kontekst mu se šalje izričito|da, uvek|dobija samo system prompt koordinatora|dobija poslednju poruku",
            "Subagent je zanemario važna ograničenja zadatka. Najverovatniji uzrok?|koordinator mu ih nije naveo u zadatku|subagent koristi drugi model|premali max_tokens|previše alata",
            "Koja je glavna prednost subagenata?|rade u odvojenom kontekstu, pa glavni ostaje čist|jeftiniji su po tokenu|uvek su brži|ne trebaju im alati",
            "Ko u obrascu koordinator i subagenti spaja rezultate u konačan odgovor?|koordinator|svaki subagent sam|korisnik|MCP server",
            "Kada se podzadaci mogu pustiti paralelno na više subagenata?|kad ne zavise jedan od drugog|uvek|nikada|samo preko Batch API-ja",
            "Istraživački sistem preskoči čitave delove teme. Najčešći uzrok?|koordinator je loše podelio temu na podzadatke|subagenti su prespori|keš je istekao|temperatura je preniska",
            "Šta je prompt chaining?|zadatak se deli na korake, izlaz jednog ide u sledeći|isti prompt se šalje više puta|spaja se više modela|prompt se kešira",
            "Kada je fiksni tok (workflow) bolji od autonomnog agenta?|kad su koraci unapred poznati i predvidivi|kad je zadatak otvoren|kad ima mnogo alata|uvek",
            "Šta je Claude Agent SDK?|biblioteka sa agentskom petljom i alatima kao u Claude Code-u|grafički editor promptova|vektorska baza|model za slike",
            "Kako agent nastavlja posao kroz više sesija bez gubitka napretka?|čuva stanje u fajlu ili bazi i učita ga na početku|oslanja se na pamćenje modela|povećava temperaturu|nikako",
            "Agent za podršku odobrava povraćaj novca iznad dozvoljenog. Najpouzdanija zaštita?|provera u kodu, hook ili alat, koja blokira iznos preko limita|strožija rečenica u promptu|niža temperatura|više primera u promptu",
            "Kada agent za podršku treba da preda slučaj čoveku?|po jasnim pravilima, npr. iznos, vrsta problema ili zahtev kupca|kad sam proceni da je nesiguran|nikad|posle deset poruka",
            "Kupac izričito traži da razgovara sa čovekom. Šta agent radi?|predaje slučaj čoveku|još jednom pokuša sam da reši|ignoriše zahtev|završava razgovor",
            "Zašto se eskalacija ne zasniva na tome koliko model kaže da je siguran?|samoprocena modela nije pouzdana|to je skupo|API to ne dozvoljava|to usporava odgovor",
            "Šta je najbolje predati čoveku pri eskalaciji?|kratak strukturisan rezime: problem, šta je urađeno, šta treba|ceo sirovi transkript|samo poslednju poruku|ništa",
            // Claude Code
            "Koji hook se pokreće pre poziva alata i može da ga blokira?|PreToolUse|PostToolUse|Stop|SessionStart",
            "Koji hook se pokreće posle uspešnog poziva alata?|PostToolUse|PreToolUse|UserPromptSubmit|Notification",
            "Koji hook se pokreće kad korisnik pošalje poruku?|UserPromptSubmit|PreToolUse|SessionStart|Stop",
            "Koji hook se pokreće kad počne sesija?|SessionStart|Stop|PreCompact|SubagentStop",
            "Koji hook se pokreće kad Claude završi odgovor?|Stop|SessionStart|PreToolUse|UserPromptSubmit",
            "Kojim izlaznim kodom PreToolUse hook blokira poziv alata?|2",
            "Po čemu se hook razlikuje od pravila u CLAUDE.md?|hook se izvrši uvek, a pravilo model može da prekrši|nema razlike|CLAUDE.md je strožiji|hook radi samo u CI",
            "Gde se podešavaju hook-ovi u Claude Code-u?|u settings.json|u CLAUDE.md|u .mcp.json|u package.json",
            "Koji fajl Claude Code sam učitava kao uputstva za projekat?|CLAUDE.md|README.md|PROMPT.md|.gitignore",
            "Gde stoje lična uputstva koja važe za sve tvoje projekte?|~/.claude/CLAUDE.md|CLAUDE.md u repozitorijumu|.mcp.json|~/.gitconfig",
            "Kolega ne dobija pravila koja ti dobijaš. Najverovatnije?|pravila su u tvom ~/.claude/CLAUDE.md, a ne u repozitorijumu|model ih ignoriše|fajl je prevelik|kolega ima drugi model",
            "Kako CLAUDE.md uvozi sadržaj drugog fajla?|@putanja/do/fajla|#include fajl|import: fajl|{{fajl}}",
            "Gde stoje timska podešavanja Claude Code-a koja idu u git?|.claude/settings.json|.claude/settings.local.json|~/.claude/settings.json|CLAUDE.md",
            "Gde stoje tvoja lična podešavanja za projekat koja ne idu u git?|.claude/settings.local.json|.claude/settings.json|.mcp.json|CLAUDE.md",
            "Koja podešavanja Claude Code-a imaju najveći prioritet?|managed podešavanja organizacije|korisnička ~/.claude/settings.json|projektna .claude/settings.json|.claude/settings.local.json",
            "Gde se nalaze Agent Skills projekta?|.claude/skills/, svaki sa SKILL.md fajlom|.mcp.json|.claude/hooks/|CLAUDE.md",
            "Po čemu Claude odlučuje kada da učita neki skill?|po opisu (description) u SKILL.md|nasumično|uvek učita sve|po veličini fajla",
            "Gde se definišu subagenti projekta u Claude Code-u?|Markdown fajlovi u .claude/agents/|.mcp.json|hook u settings.json|naslov u CLAUDE.md",
            "Šta radi plan mode?|Claude istražuje i predlaže plan, a ne menja fajlove|izvršava sve bez pitanja|pokreće testove|pravi git granu",
            "Kada je plan mode najkorisniji?|za veće izmene sa više mogućih pristupa|za ispravku jednog slova|za čitanje loga|nikada",
            "Kako se Claude Code pokreće bez interakcije, npr. u CI?|claude -p \"zadatak\"|claude --interactive|claude --watch|claude ci",
            "Koji izlaz Claude Code-a je zgodan za mašinsku obradu u CI?|--output-format json|--output-format text|--verbose|--color",
            "Šta radi komanda /compact?|sažima dosadašnji razgovor da oslobodi kontekst|briše fajlove|komprimuje repozitorijum|zatvara sesiju",
            "Šta radi komanda /clear?|briše istoriju razgovora i kreće iz čistog konteksta|briše git istoriju|briše fajlove projekta|menja model",
            "Zašto review koda raditi u novoj sesiji, a ne u onoj koja je kod pisala?|nova sesija ne nosi pretpostavke autora pa lakše vidi greške|jeftinije je|brže je|tako zahteva git",
            // Promptovi i strukturisan izlaz
            "Koje tool_choice podešavanje tera Claude da pozove bilo koji alat?|any|auto|none|required",
            "Koje tool_choice podešavanje važi kad se zadaju alati, a ništa ne izabere?|auto|any|none|tool",
            "Kako naterati Claude da pozove tačno određeni alat?|tool_choice tipa tool sa imenom alata|tool_choice auto|staviti alat prvi na listu|zamoliti ga u promptu",
            "Najpouzdaniji način da Claude vrati JSON po šemi?|structured outputs ili alat sa šemom i obaveznim pozivom|zamoliti „vrati JSON“|niža temperatura|duži prompt",
            "JSON odgovara šemi, ali su vrednosti pogrešne. Šta pomaže?|provera smisla u kodu i ponovni pokušaj sa opisom greške|strožija JSON šema|veći max_tokens|druga temperatura",
            "Šta je validation-retry petlja?|proveri se izlaz, a greška se vrati Claude-u da ispravi|isti zahtev se ponovi bez izmena|digne se temperatura|pređe se na drugi model",
            "Šta je few-shot prompting?|nekoliko primera ulaza i željenog izlaza u promptu|jedan kratak prompt|više modela odjednom|niska temperatura",
            "Kada few-shot primeri najviše pomažu?|za dosledan format i nejasne granične slučajeve|za brže odgovore|za manju cenu|nikad",
            "Zašto se u promptovima koriste XML tagovi?|jasno odvajaju delove, npr. dokument od uputstava|obavezni su|smanjuju cenu|menjaju model",
            "Čemu služi system prompt?|daje ulogu, pravila i kontekst za ceo razgovor|čuva istoriju|bira model|ograničava tokene",
            "Polje u dokumentu nekad ne postoji. Kako sprečiti da ga model izmisli?|u šemi ga označiti kao opciono ili nullable|napraviti ga obaveznim|izbaciti polje|staviti mu podrazumevanu vrednost",
            "Kako smanjiti izmišljanje pri izvlačenju podataka iz dokumenta?|dozvoliti „nepoznato“ i tražiti citat iz izvora|tražiti duži odgovor|višom temperaturom|izbaciti system prompt",
            "Review agent prijavljuje previše lažnih problema. Prvi korak?|precizno navesti u promptu šta se prijavljuje, a šta ne|dodati još jednog agenta|povećati temperaturu|ugasiti review",
            "Šta radi parametar stop_sequences?|zaustavlja odgovor kad se pojavi zadati tekst|briše tekst|ubrzava model|kešira odgovor",
            "Šta kontroliše temperature?|koliko je izbor reči nasumičan|dužinu odgovora|brzinu|cenu",
            "Koji parametar ograničava dužinu odgovora?|max_tokens|temperature|top_k|stop_reason",
            "Šta je extended thinking?|model dobija prostor da razmisli pre konačnog odgovora|više odgovora odjednom|keširanje promptova|grupna obrada",
            // Alati i MCP
            "Na osnovu čega Claude najviše bira koji alat da pozove?|imena i opisa alata|redosleda u listi|veličine šeme|nasumično",
            "Claude meša dva slična alata. Najjednostavnije rešenje?|jasniji opisi alata, kada se koji koristi|poseban klasifikator za rutiranje|još alata|drugi model",
            "Zašto ne dati jednom agentu pedeset alata?|previše alata otežava izbor i troši kontekst|API to ne dozvoljava|sporiji je internet|alati se plaćaju po komadu",
            "U kom formatu se opisuje ulaz alata za Claude?|JSON Schema|XML DTD|YAML|Protobuf",
            "Kako se zove polje sa šemom ulaza u definiciji alata?|input_schema|parameters|schema|args",
            "Šta znači skraćenica MCP?|Model Context Protocol|Multi Claude Platform|Machine Code Pipeline|Model Control Panel",
            "Šta je MCP?|otvoren protokol za povezivanje modela sa alatima i podacima|Anthropic-ov model|baza podataka|programski jezik",
            "Koje su tri osnovne stvari koje MCP server nudi?|alati, resursi i promptovi|modeli, ključevi i tokeni|tabele, upiti i indeksi|niti, procesi i fajlovi",
            "Po čemu se MCP alat razlikuje od MCP resursa?|alat izvršava akciju, resurs daje podatke za čitanje|nema razlike|resurs piše u bazu|alat sme samo da čita",
            "Katalog proizvoda koji se samo čita najbolje je izložiti kao?|MCP resurs|MCP alat|MCP prompt|hook",
            "Šta je MCP prompt?|gotov šablon poruke koji server nudi|system prompt modela|log servera|lozinka",
            "Koji fajl definiše MCP servere projekta za ceo tim?|.mcp.json|.claude/settings.local.json|~/.claude.json|CLAUDE.md",
            "Gde Claude Code čuva MCP servere koji su samo tvoji (user scope)?|~/.claude.json|.mcp.json u repozitorijumu|CLAUDE.md|.gitignore",
            "Kako bezbedno navesti API ključ u .mcp.json?|preko promenljive okruženja, npr. ${API_KEY}|upisati ključ direktno|u CLAUDE.md|u ime servera",
            "Koji MCP transport se koristi za lokalni server pokrenut kao proces?|stdio|Streamable HTTP|FTP|SMTP",
            "Koji MCP transport se preporučuje za udaljeni server?|Streamable HTTP|stdio|FTP|SMTP",
            "Kako izgleda ime MCP alata u Claude Code-u?|mcp__server__alat|server.alat|alat@server|/server/alat",
            "Alat vraća ogroman odgovor sa nebitnim poljima. Šta je dobro?|da alat vraća samo polja potrebna za zadatak|veći kontekst|ignorisati to|dodati još alata",
            "Kakva je dobra poruka greške iz alata?|kaže šta nije uspelo i šta može da se uradi|samo „Error“|prazna|stack trace bez objašnjenja",
            "Pretraga ne nađe ništa. Kako to alat treba da vrati?|kao uspešan rezultat sa praznom listom, ne kao grešku|kao grešku|da ne vrati ništa|da izmisli rezultat",
            // Kontekst, cena i pouzdanost
            "Šta je „lost in the middle“?|model slabije koristi podatke iz sredine dugog konteksta|gubitak poruka u mreži|brisanje konteksta|greška API-ja",
            "Gde Anthropic preporučuje da stoje dugi dokumenti u promptu?|na vrhu, a pitanje na kraju|na kraju, posle pitanja|u sredini|u posebnoj poruci posle odgovora",
            "U dugoj sesiji agent zaboravlja utvrđene činjenice (iznose, datume). Rešenje?|držati ih u posebnom bloku koji se šalje uz svaki zahtev|duži system prompt|veća temperatura|još alata",
            "Šta pomaže kad se dug razgovor približi limitu konteksta?|sažimanje (compaction) starijeg dela razgovora|veća temperatura|ponovo poslati sve|još alata",
            "Za koliko Message Batches API smanjuje cenu?|50%|10%|25%|90%",
            "U kom roku se najkasnije obrađuju batch zahtevi?|24 sata|1 sat|7 dana|5 minuta",
            "Noćna obrada 50.000 dokumenata, niko ne čeka odgovor. Najbolji izbor?|Message Batches API|pojedinačni pozivi jedan po jedan|streaming|najveći model",
            "Da li je Message Batches API dobar za chat uživo?|ne, rezultat može da kasni do 24 sata|da|samo vikendom|samo uz keširanje",
            "Koliko košta čitanje iz prompt keša u odnosu na običan ulaz?|10% cene|50% cene|isto|duplo",
            "Koliko košta upis u prompt keš od 5 minuta u odnosu na običan ulaz?|25% skuplje|isto|50% jeftinije|deset puta skuplje",
            "Koliko podrazumevano traje prompt keš?|5 minuta|1 sat|24 sata|30 sekundi",
            "Kojim poljem se označava dokle se prompt kešira?|cache_control|cache_key|keep_alive|memo",
            "Šta se isplati keširati?|stalni početak prompta: alate, system prompt, duge dokumente|poslednju poruku korisnika|nasumične delove|odgovor modela",
            "Zašto promena na početku prompta kvari keš?|keš radi na istom prefiksu, pa promena poništava sve posle nje|keš traje sekundu|keš važi samo za izlaz|keš je po korisniku",
            "Gde treba da stoji API ključ za Claude?|u promenljivoj okruženja ili menadžeru tajni|u kodu repozitorijuma|u CLAUDE.md|u promptu",
            // Messages API
            "Na koji endpoint se šalju poruke Claude API-ju?|/v1/messages|/v1/completions|/v1/chat|/v1/generate",
            "Koje uloge postoje u nizu messages kod Claude API-ja?|user i assistant|user, assistant i system|human i ai|client i server",
            "Gde se u Messages API zadaje system prompt?|u posebnom parametru system|kao poruka sa ulogom system|u HTTP zaglavlju|u adresi",
            "U kom HTTP zaglavlju se šalje Claude API ključ?|x-api-key|api-token|anthropic-key|Cookie",
            "Koja porodica Claude modela je najbrža i najjeftinija?|Haiku|Opus|Sonnet|Gemini",
    };

    /** Nazivi grupa, istim redom kao GROUPS. */
    static final String[] NAMES = {
            "Zagonetka", "Pitalica", "Opšta kultura", "Književnost", "Priroda i nauka",
            "Gde se nalazi", "Srbija", "Sport", "Jezik", "Valute",
            "Java backend", "Claude sertifikat (CCAF)",
    };

    static final String[][] GROUPS = {
            ZAGONETKE, PITALICE, OPSTA_KULTURA, KNJIZEVNOST, PRIRODA,
            GDE_SE_NALAZI, SRBIJA, SPORT, JEZIK, VALUTE,
            JAVA, CLAUDE,
    };

    /** Prvih GENERAL grupa je opšte znanje; JAVA i CLAUDE na kraju imaju svoj udeo u Quiz.any. */
    static final int GENERAL = 10;

    static final String[] CONTINENTS = {
            "Evropa", "Azija", "Afrika", "Severna Amerika", "Južna Amerika", "Australija i Okeanija",
    };

    /**
     * „Država|glavni grad|kontinent“. Kontinent se izostavlja kod država koje su na dva kontinenta,
     * pa se za njih ne postavlja pitanje o kontinentu. Izostavljene su države čiji se glavni grad
     * zove isto kao država ili oko kog postoji spor.
     */
    static final String[] COUNTRIES = {
            "Srbija|Beograd|Evropa",
            "Hrvatska|Zagreb|Evropa",
            "Bosna i Hercegovina|Sarajevo|Evropa",
            "Crna Gora|Podgorica|Evropa",
            "Severna Makedonija|Skoplje|Evropa",
            "Slovenija|Ljubljana|Evropa",
            "Bugarska|Sofija|Evropa",
            "Rumunija|Bukurešt|Evropa",
            "Mađarska|Budimpešta|Evropa",
            "Grčka|Atina|Evropa",
            "Albanija|Tirana|Evropa",
            "Italija|Rim|Evropa",
            "Francuska|Pariz|Evropa",
            "Nemačka|Berlin|Evropa",
            "Austrija|Beč|Evropa",
            "Švajcarska|Bern|Evropa",
            "Španija|Madrid|Evropa",
            "Portugalija|Lisabon|Evropa",
            "Velika Britanija|London|Evropa",
            "Irska|Dablin|Evropa",
            "Holandija|Amsterdam|Evropa",
            "Belgija|Brisel|Evropa",
            "Danska|Kopenhagen|Evropa",
            "Švedska|Stokholm|Evropa",
            "Norveška|Oslo|Evropa",
            "Finska|Helsinki|Evropa",
            "Island|Rejkjavik|Evropa",
            "Poljska|Varšava|Evropa",
            "Češka|Prag|Evropa",
            "Slovačka|Bratislava|Evropa",
            "Ukrajina|Kijev|Evropa",
            "Belorusija|Minsk|Evropa",
            "Litvanija|Viljnus|Evropa",
            "Letonija|Riga|Evropa",
            "Estonija|Talin|Evropa",
            "Moldavija|Kišinjev|Evropa",
            "Malta|Valeta|Evropa",
            "Rusija|Moskva",
            "Turska|Ankara",
            "Kipar|Nikozija",
            "Gruzija|Tbilisi",
            "Jermenija|Jerevan",
            "Azerbejdžan|Baku",
            "Kazahstan|Astana",
            "Kina|Peking|Azija",
            "Japan|Tokio|Azija",
            "Južna Koreja|Seul|Azija",
            "Severna Koreja|Pjongjang|Azija",
            "Indija|Nju Delhi|Azija",
            "Pakistan|Islamabad|Azija",
            "Bangladeš|Daka|Azija",
            "Nepal|Katmandu|Azija",
            "Tajland|Bangkok|Azija",
            "Vijetnam|Hanoj|Azija",
            "Filipini|Manila|Azija",
            "Malezija|Kuala Lumpur|Azija",
            "Mongolija|Ulan Bator|Azija",
            "Uzbekistan|Taškent|Azija",
            "Avganistan|Kabul|Azija",
            "Iran|Teheran|Azija",
            "Irak|Bagdad|Azija",
            "Sirija|Damask|Azija",
            "Liban|Bejrut|Azija",
            "Jordan|Aman|Azija",
            "Saudijska Arabija|Rijad|Azija",
            "Ujedinjeni Arapski Emirati|Abu Dabi|Azija",
            "Katar|Doha|Azija",
            "Kambodža|Pnom Pen|Azija",
            "Laos|Vijentijan|Azija",
            "Egipat|Kairo|Afrika",
            "Maroko|Rabat|Afrika",
            "Libija|Tripoli|Afrika",
            "Nigerija|Abudža|Afrika",
            "Gana|Akra|Afrika",
            "Kenija|Najrobi|Afrika",
            "Etiopija|Adis Abeba|Afrika",
            "Tanzanija|Dodoma|Afrika",
            "Uganda|Kampala|Afrika",
            "Angola|Luanda|Afrika",
            "Senegal|Dakar|Afrika",
            "Sudan|Kartum|Afrika",
            "Zimbabve|Harare|Afrika",
            "Zambija|Lusaka|Afrika",
            "Madagaskar|Antananarivo|Afrika",
            "Kamerun|Jaunde|Afrika",
            "Mali|Bamako|Afrika",
            "Demokratska Republika Kongo|Kinšasa|Afrika",
            "Ruanda|Kigali|Afrika",
            "Somalija|Mogadiš|Afrika",
            "Mozambik|Maputo|Afrika",
            "Namibija|Vindhuk|Afrika",
            "Bocvana|Gaborone|Afrika",
            "SAD|Vašington|Severna Amerika",
            "Kanada|Otava|Severna Amerika",
            "Meksiko|Meksiko Siti|Severna Amerika",
            "Kuba|Havana|Severna Amerika",
            "Jamajka|Kingston|Severna Amerika",
            "Kostarika|San Hoze|Severna Amerika",
            "Honduras|Tegusigalpa|Severna Amerika",
            "Nikaragva|Managva|Severna Amerika",
            "Dominikanska Republika|Santo Domingo|Severna Amerika",
            "Haiti|Port o Prens|Severna Amerika",
            "Brazil|Brazilija|Južna Amerika",
            "Argentina|Buenos Ajres|Južna Amerika",
            "Čile|Santjago|Južna Amerika",
            "Peru|Lima|Južna Amerika",
            "Kolumbija|Bogota|Južna Amerika",
            "Venecuela|Karakas|Južna Amerika",
            "Ekvador|Kito|Južna Amerika",
            "Paragvaj|Asunsion|Južna Amerika",
            "Urugvaj|Montevideo|Južna Amerika",
            "Australija|Kanbera|Australija i Okeanija",
            "Novi Zeland|Velington|Australija i Okeanija",
            "Fidži|Suva|Australija i Okeanija",
            "Papua Nova Gvineja|Port Morzbi|Australija i Okeanija",
    };
}
