package com.cuvar.app;

/**
 * Banka pitanja za otključavanje. Svako pitanje je jedan red:
 *   "Pitanje|tačan odgovor|netačan|netačan|netačan"  (ponuđeni odgovori, redosled se meša)
 *   "Pitanje|broj"                                    (odgovor je broj koji se kuca)
 * Novo pitanje se dodaje kao novi red u odgovarajuću grupu. Nova grupa se dodaje u NAMES i GROUPS.
 * tests/com/cuvar/app/QuizTest.java proverava da je svaki red ispravno zapisan.
 */
final class QuizBank {

    private QuizBank() {
    }

    static final String[] ZAGONETKE = {
            "Ima zube, a ne jede. Šta je to?|češalj|kašika|olovka|čaša",
            "Što se više suši, to je mokriji. Šta je to?|peškir|kišobran|jastuk|lonac",
            "Ima dirke, a ne otvara nijedna vrata. Šta je to?|klavir|kapija|brava|ormar",
            "Kuca, a nije srce; ide, a nema noge. Šta je to?|sat|voz|bubanj|čekić",
            "Ima glavu i rep, a nema telo. Šta je to?|novčić|zmija|crv|miš",
            "Što više uzmeš, to više ostavljaš za sobom. Šta je to?|koraci|novac|vreme|hrana",
            "Ima jedno oko, a ne vidi. Šta je to?|igla|dugme|ključ|olovka",
            "Što je ima više, to manje vidiš. Šta je to?|mrak|svetlost|kuća|planina",
            "Leti bez krila, plače bez očiju. Šta je to?|oblak|ptica|avion|vetar",
            "Raste naopačke, glavom nadole. Šta je to?|ledenica|drvo|cvet|trava",
            "Ima vrat, a nema glavu. Šta je to?|flaša|žirafa|lampa|stolica",
            "Ima četiri noge, a ne hoda. Šta je to?|sto|pas|mačka|pauk",
            "Puno rupa, a ipak drži vodu. Šta je to?|sunđer|sito|kofa|lonac",
            "Pripada tebi, a drugi ga koriste više nego ti. Šta je to?|ime|telefon|automobil|kuća",
            "Čim izgovoriš njeno ime, nestane. Šta je to?|tišina|tajna|eho|senka",
            "Ide gore i dole, a ne pomera se s mesta. Šta je to?|stepenice|lift|klackalica|lopta",
            "Ima gradove bez kuća, reke bez vode i šume bez drveća. Šta je to?|mapa|pustinja|slika|knjiga",
            "Ujutru hoda na četiri noge, u podne na dve, a uveče na tri. Ko je to?|čovek|pas|konj|ptica",
            "Ima lice i dve ruke, a nema nogu. Šta je to?|sat|lutka|robot|statua",
            "Vodi kroz grad i polja, a nikad se ne pomeri. Šta je to?|put|reka|voz|vetar",
            "Okruglo i žuto, greje, a daleko je. Šta je to?|sunce|mesec|lopta|limun",
            "Polje belo, seme crno; ko ga seje, taj i zna. Šta je to?|knjiga|sneg|šahovska tabla|njiva",
            "I zimi i leti isto je obučena. Šta je to?|jelka|hrast|lipa|breza",
            "Spolja zelena, iznutra crvena, a seme crno. Šta je to?|lubenica|paradajz|jabuka|krastavac",
            "Ima šešir, a nema glavu; ima nogu, a nema cipelu. Šta je to?|pečurka|ekser|kišobran|lampa",
            "Ima krila, a nije ptica; leti, a nije živo. Šta je to?|avion|leptir|pčela|šišmiš",
            "Lakše je od pera, a niko ga ne može zadržati ni par minuta. Šta je to?|dah|kamen|olovka|knjiga",
            "Može da se slomi, a da ga niko ni ne dotakne. Šta je to?|obećanje|staklo|tanjir|jaje",
            "Otvara se kad pada kiša. Šta je to?|kišobran|prozor|cvet|knjiga",
            "Uvek je ispred tebe, a ne možeš je videti. Šta je to?|budućnost|nos|ogledalo|senka",
            "Ima oči, a ne vidi; raste u zemlji. Šta je to?|krompir|šargarepa|crv|koren",
            "Dan i noć stoji pred kućom, ne jede i ne spava, a čuva. Šta je to?|ograda|pas|mačka|stražar",
            "Belo kao sneg, a nije sneg; slatko kao med, a nije med. Šta je to?|šećer|so|brašno|mleko",
            "Bez nogu ide, bez ruku vrata otvara. Šta je to?|vetar|voda|duh|mačka",
            "Ide u vodu, a ne pokvasi se. Šta je to?|senka|riba|kamen|čamac",
            "Sto braće u jednoj kući spava. Šta je to?|šibice|zubi|olovke|pčele",
            "Nema noge, a trči; nema usta, a žubori. Šta je to?|potok|vetar|sat|voz",
            "Svako ga ima, a niko ga ne može prodati ni pokloniti. Šta je to?|senka|novac|kuća|igračka",
            "Jede, a nikad nije sit; pije vodu i umre. Šta je to?|vatra|pas|biljka|riba",
            "Ima mnogo listova, a nije drvo. Šta je to?|knjiga|kupus|salata|novine",
            "Kad se rodi, veliko je; kad ostari, malo je. Šta je to?|sveća|drvo|čovek|reka",
            "Šta se nalazi u sredini Pariza?|slovo R|Ajfelov toranj|Sena|Luvr",
            "Čega ima jednom u minutu, dva puta u momentu, a nijednom u sto godina?|slova M|sekunde|sata|dana",
    };

    static final String[] PITALICE = {
            "Šta je teže: kilogram perja ili kilogram gvožđa?|isto su teški|perje|gvožđe|zavisi od vetra",
            "Ako u trci prestigneš drugog, koji si?|drugi|prvi|treći|poslednji",
            "Petar ima tri ćerke, a svaka ima po jednog brata. Koliko dece ima Petar?|4",
            "Koliko meseci u godini ima 28 dana?|12",
            "Koliko jaja možeš da pojedeš na prazan stomak?|1",
            "Električni voz ide na sever, a vetar duva na jug. Na koju stranu ide dim?|nema dima|na sever|na jug|na istok",
            "Koje boje je takozvana crna kutija u avionu?|narandžasta|crna|bela|siva",
            "Koliko je životinja Mojsije poveo u barku?|nijednu, to je bio Noje|po dve od svake|sedam|stotinu",
            "Seljak ima 17 ovaca. Sve osim 9 su pobegle. Koliko mu je ostalo?|9",
            "Imaš 3 jabuke i uzmeš 2. Koliko jabuka ti imaš?|2",
            "Lekar ti da 3 tablete i kaže da piješ jednu na svakih pola sata. Za koliko minuta ćeš popiti sve?|60",
            "Koliko puta možeš da oduzmeš 5 od 25?|1",
            "Koja reč je u rečniku uvek napisana pogrešno?|pogrešno|tačno|rečnik|nijedna",
            "U mračnoj sobi imaš šibicu, sveću, lampu na ulje i peć. Šta prvo pališ?|šibicu|sveću|lampu|peć",
            "Šta se nalazi između neba i zemlje?|slovo I|vazduh|oblaci|ptice",
            "Kada je 10 + 3 = 1?|kad gledaš na sat|nikada|u ponoć|kad je prestupna godina",
            "Petao snese jaje na vrh krova. Na koju stranu jaje padne?|petao ne nosi jaja|levo|desno|ostaje na krovu",
            "Šta možeš da držiš u desnoj ruci, a nikako u levoj?|levi lakat|olovku|loptu|telefon",
            "Koliko slova ima reč „azbuka“?|6",
            "Koliko je pola od pola od 100?|25",
            "Koliko je 2 + 2 × 2?|6",
            "Koliko nogu imaju dve kokoške i tri psa zajedno?|16",
            "Polovina broja je 15. Koji je to broj?|30",
            "Brat i sestra imaju zajedno 10 godina, a brat je stariji 4 godine. Koliko godina ima sestra?|3",
            "Puž se penje uz stub od 10 metara: danju 3 m gore, noću 2 m dole. Kog dana stiže na vrh?|8",
            "Ako 5 mašina za 5 minuta napravi 5 proizvoda, za koliko minuta 100 mašina napravi 100 proizvoda?|5",
            "Lopta i palica koštaju 110 dinara. Palica je skuplja od lopte 100 dinara. Koliko košta lopta?|5",
    };

    static final String[] OPSTA_KULTURA = {
            "Ko je naslikao Mona Lizu?|Leonardo da Vinči|Mikelanđelo|Pablo Pikaso|Vinsent van Gog",
            "Ko je naslikao „Zvezdanu noć“?|Vinsent van Gog|Klod Mone|Salvador Dali|Rembrant",
            "Ko je oslikao tavanicu Sikstinske kapele?|Mikelanđelo|Rafaelo|Leonardo da Vinči|Botičeli",
            "Ko je komponovao „Mesečevu sonatu“?|Ludvig van Betoven|Volfgang Amadeus Mocart|Johan Sebastijan Bah|Frederik Šopen",
            "Ko je komponovao operu „Čarobna frula“?|Volfgang Amadeus Mocart|Đuzepe Verdi|Ludvig van Betoven|Petar Iljič Čajkovski",
            "Ko je komponovao balet „Labudovo jezero“?|Petar Iljič Čajkovski|Igor Stravinski|Johan Štraus|Antonio Vivaldi",
            "Ko je komponovao „Četiri godišnja doba“?|Antonio Vivaldi|Johan Sebastijan Bah|Đuzepe Verdi|Franc Šubert",
            "Koliko žica ima obična gitara?|6",
            "Koliko dirki ima standardni klavir?|88",
            "Koliko boja ima duga?|7",
            "Koja boja nastaje mešanjem plave i žute?|zelena|ljubičasta|narandžasta|braon",
            "Koja boja nastaje mešanjem crvene i bele?|roze|ljubičasta|narandžasta|siva",
            "Koliko je godina u jednom veku?|100",
            "Koliko je godina u jednom milenijumu?|1000",
            "Koliko dana ima prestupna godina?|366",
            "Koliko sati ima jedna nedelja?|168",
            "Koliko sekundi ima jedan sat?|3600",
            "Koliko minuta ima jedan dan?|1440",
            "Koji mesec u godini ima najmanje dana?|februar|april|novembar|jun",
            "Koji je prvi dan proleća po kalendaru?|21. mart|1. mart|21. april|1. maj",
            "Ko je izmislio telefon (prvi patent)?|Aleksandar Grejem Bel|Nikola Tesla|Tomas Edison|Guljelmo Markoni",
            "Ko je formulisao teoriju relativnosti?|Albert Ajnštajn|Isak Njutn|Galileo Galilej|Nikola Tesla",
            "Ko je otkrio penicilin?|Aleksandar Fleming|Luj Paster|Marija Kiri|Čarls Darvin",
            "Ko je postavio teoriju evolucije prirodnom selekcijom?|Čarls Darvin|Gregor Mendel|Isak Njutn|Luj Paster",
            "Koja naučnica je dobila Nobelovu nagradu i za fiziku i za hemiju?|Marija Kiri|Ada Lavlejs|Rozalind Frenklin|Lize Majtner",
            "Ko je prvi kročio na Mesec?|Nil Armstrong|Jurij Gagarin|Baz Oldrin|Majkl Kolins",
            "Ko je bio prvi čovek u svemiru?|Jurij Gagarin|Nil Armstrong|Valentina Tereškova|Džon Glen",
            "Koje godine je čovek prvi put sleteo na Mesec?|1969",
            "Ko je otkrio Ameriku 1492. godine?|Kristofor Kolumbo|Vasko da Gama|Fernando Magelan|Marko Polo",
            "Na kom brodu je putovao Kolumbo kada je stigao do Amerike?|Santa Marija|Titanik|Mejflauer|Viktorija",
            "Koje godine je potonuo Titanik?|1912",
            "Koje godine je počeo Prvi svetski rat?|1914",
            "Koje godine je završen Drugi svetski rat?|1945",
            "Koje godine je pao Berlinski zid?|1989",
            "Koliko ima znakova Zodijaka?|12",
            "Iz koje zemlje potiče pica?|Italija|Grčka|Francuska|Španija",
            "Iz koje zemlje potiču suši?|Japan|Kina|Koreja|Tajland",
            "Iz koje zemlje potiče paela?|Španija|Italija|Portugalija|Meksiko",
            "Kako se zove čuveni muzej u Parizu u kome je Mona Liza?|Luvr|Prado|Ermitaž|Britanski muzej",
            "Koji je simbol mira?|golub sa maslinovom grančicom|orao|lav|soko",
            "Šta znači skraćenica „npr.“?|na primer|na pristojan red|nema problema|naš prijatelj",
            "Koliko karata ima standardni špil (bez džokera)?|52",
            "Koliko tačkica ukupno ima obična kockica za igru?|21",
            "Koliko figura ima svaki igrač na početku partije šaha?|16",
            "Kako se zove crtani lik, mornar koji jede spanać?|Popaj|Paja Patak|Miki Maus|Duško Dugouško",
            "Kako se zove Mikijev pas?|Pluton|Šilja|Dugouško|Tom",
            "Koliko patuljaka ima u bajci o Snežani?|7",
            "Ko je napisao bajku „Ružno pače“?|Hans Kristijan Andersen|braća Grim|Šarl Pero|Ezop",
            "Ko je napisao „Pepeljugu“ u verziji sa staklenom cipelicom?|Šarl Pero|Hans Kristijan Andersen|braća Grim|Ezop",
    };

    static final String[] KNJIZEVNOST = {
            "Ko je napisao „Na Drini ćuprija“?|Ivo Andrić|Meša Selimović|Branislav Nušić|Danilo Kiš",
            "Koji pisac sa ovih prostora je dobio Nobelovu nagradu za književnost 1961. godine?|Ivo Andrić|Miloš Crnjanski|Meša Selimović|Dobrica Ćosić",
            "Ko je napisao „Gorski vijenac“?|Petar II Petrović Njegoš|Vuk Karadžić|Laza Kostić|Jovan Jovanović Zmaj",
            "Ko je napisao „Derviš i smrt“?|Meša Selimović|Ivo Andrić|Borislav Pekić|Danilo Kiš",
            "Ko je napisao „Seobe“?|Miloš Crnjanski|Ivo Andrić|Borislav Pekić|Dobrica Ćosić",
            "Ko je napisao „Sumnjivo lice“?|Branislav Nušić|Jovan Sterija Popović|Stevan Sremac|Radoje Domanović",
            "Ko je napisao „Gospođu ministarku“?|Branislav Nušić|Jovan Sterija Popović|Borislav Stanković|Laza Lazarević",
            "Ko je napisao „Pop Ćira i pop Spira“?|Stevan Sremac|Branislav Nušić|Janko Veselinović|Simo Matavulj",
            "Ko je napisao „Nečistu krv“?|Borisav Stanković|Stevan Sremac|Ivo Andrić|Milovan Glišić",
            "Ko je napisao pesmu „Santa Maria della Salute“?|Laza Kostić|Jovan Dučić|Aleksa Šantić|Đura Jakšić",
            "Koji pesnik je deci poznat kao „Čika Jova“?|Jovan Jovanović Zmaj|Dušan Radović|Branko Ćopić|Desanka Maksimović",
            "Ko je napisala pesmu „Krvava bajka“?|Desanka Maksimović|Isidora Sekulić|Vesna Parun|Mira Alečković",
            "Ko je napisao „Orlovi rano lete“?|Branko Ćopić|Dušan Radović|Grigor Vitez|Ivo Andrić",
            "Ko je napisao „Hazarski rečnik“?|Milorad Pavić|Danilo Kiš|Borislav Pekić|David Albahari",
            "Ko je napisao „Grobnicu za Borisa Davidoviča“?|Danilo Kiš|Milorad Pavić|Ivo Andrić|Mihailo Lalić",
            "Ko je napisao „Kapetana Džona Piplfoksa“?|Dušan Kovačević|Branislav Nušić|Ljubomir Simović|Aleksandar Popović",
            "Ko je napisao „Maratonci trče počasni krug“?|Dušan Kovačević|Branislav Nušić|Ljubomir Simović|Borislav Pekić",
            "Ko je reformisao srpski jezik i azbuku?|Vuk Stefanović Karadžić|Dositej Obradović|Sveti Sava|Branko Radičević",
            "Po kom načelu je Vuk reformisao pravopis?|Piši kao što govoriš|Jedno slovo, dva glasa|Piši kako je lepo|Svaki glas dva slova",
            "Ko je napisao „Romea i Juliju“?|Vilijam Šekspir|Čarls Dikens|Johan Volfgang Gete|Dante Aligijeri",
            "Ko je napisao „Hamleta“?|Vilijam Šekspir|Kristofer Marlo|Molijer|Gete",
            "Ko je napisao „Don Kihota“?|Migel de Servantes|Lope de Vega|Dante Aligijeri|Viktor Igo",
            "Ko je napisao „Božanstvenu komediju“?|Dante Aligijeri|Đovani Bokačo|Frančesko Petrarka|Nikolo Makijaveli",
            "Ko je napisao „Rat i mir“?|Lav Tolstoj|Fjodor Dostojevski|Anton Čehov|Aleksandar Puškin",
            "Ko je napisao „Zločin i kaznu“?|Fjodor Dostojevski|Lav Tolstoj|Nikolaj Gogolj|Ivan Turgenjev",
            "Ko je napisao „Malog princa“?|Antoan de Sent Egziperi|Žil Vern|Viktor Igo|Alber Kami",
            "Ko je napisao „Jadnike“?|Viktor Igo|Onore de Balzak|Emil Zola|Aleksandar Dima",
            "Ko je napisao „Tri musketara“?|Aleksandar Dima|Viktor Igo|Žil Vern|Gistav Flober",
            "Ko je napisao „Put oko sveta za 80 dana“?|Žil Vern|Herbert Džordž Vels|Mark Tven|Aleksandar Dima",
            "Ko je napisao „Avanture Toma Sojera“?|Mark Tven|Džek London|Ernest Hemingvej|Čarls Dikens",
            "Ko je napisao „Starac i more“?|Ernest Hemingvej|Džon Stajnbek|Mark Tven|Herman Melvil",
            "Ko je napisao „Hari Potera“?|Džoan Ketlin Rouling|Džon Ronald Tolkin|Rold Dal|Klajv Stejpls Luis",
            "Ko je napisao „Gospodara prstenova“?|Džon Ronald Tolkin|Klajv Stejpls Luis|Džordž R. R. Martin|Džoan Ketlin Rouling",
            "Ko je napisao roman „1984“?|Džordž Orvel|Oldos Haksli|Rej Bredberi|Franc Kafka",
            "Ko je napisao „Proces“ i „Preobražaj“?|Franc Kafka|Herman Hese|Tomas Man|Alber Kami",
            "Ko je napisao „Ilijadu“ i „Odiseju“?|Homer|Sofokle|Platon|Ezop",
            "Ko je napisao „Fausta“?|Johan Volfgang Gete|Fridrih Šiler|Hajnrih Hajne|Tomas Man",
            "Ko je napisao „Anu Karenjinu“?|Lav Tolstoj|Fjodor Dostojevski|Anton Čehov|Maksim Gorki",
            "Kako se zove Don Kihotov verni pratilac?|Sančo Pansa|Rosinante|Dulsineja|Pinokio",
    };

    static final String[] PRIRODA = {
            "Koliko nogu ima pauk?|8",
            "Koliko nogu ima insekt?|6",
            "Koliko srca ima hobotnica?|3",
            "Koja je najveća životinja na svetu?|plavi kit|afrički slon|žirafa|bela ajkula",
            "Koja je najbrža kopnena životinja?|gepard|lav|konj|noj",
            "Koja od ovih ptica ne može da leti?|pingvin|orao|vrabac|golub",
            "Šta pčele prave od cvetnog nektara?|med|mleko|svilu|sir",
            "Koja životinja je najviša?|žirafa|slon|kamila|noj",
            "Koja životinja nosi mladunce u torbi?|kengur|medved|zec|majmun",
            "Kako se zove mladunče konja?|ždrebe|tele|jare|jagnje",
            "Kako se zove mladunče krave?|tele|ždrebe|jare|prase",
            "Kako se zove mladunče koze?|jare|jagnje|tele|štene",
            "Kako se zove mladunče ovce?|jagnje|jare|tele|ždrebe",
            "Šta jede panda najviše?|bambus|ribu|meso|travu",
            "Koja životinja menja boju da bi se sakrila?|kameleon|krokodil|kornjača|žaba",
            "Od čega se pravi svila?|od niti svilene bube|od pamuka|od vune|od lana",
            "Koliko krila ima pčela?|4",
            "Koliko očiju ima većina pauka?|8",
            "Šta je kit?|sisar|riba|gmizavac|vodozemac",
            "Šta je žaba?|vodozemac|gmizavac|sisar|riba",
            "Šta je slepi miš?|sisar|ptica|insekt|gmizavac",
            "Koji gas biljke koriste za fotosintezu?|ugljen-dioksid|kiseonik|azot|helijum",
            "Koji gas udišemo da bismo živeli?|kiseonik|ugljen-dioksid|azot|vodonik",
            "Koliko kostiju ima odrastao čovek?|206",
            "Koliko zuba ima odrastao čovek, sa umnjacima?|32",
            "Koji organ pumpa krv kroz telo?|srce|pluća|jetra|bubreg",
            "Koji je najveći organ ljudskog tela?|koža|jetra|mozak|pluća",
            "Koji organ prečišćava krv i stvara mokraću?|bubreg|srce|želudac|pluća",
            "Koliko komora ima ljudsko srce?|4",
            "Koja krvna grupa je univerzalni davalac?|0 negativna|AB pozitivna|A pozitivna|B negativna",
            "Koji vitamin telo stvara na suncu?|vitamin D|vitamin C|vitamin A|vitamin B12",
            "Kako se zove najmanja čestica hemijskog elementa?|atom|molekul|ćelija|kristal",
            "Hemijska formula vode je?|H2O|CO2|O2|NaCl",
            "Hemijski simbol zlata je?|Au|Ag|Zn|Fe",
            "Hemijski simbol srebra je?|Ag|Au|Si|Sr",
            "Hemijski simbol gvožđa je?|Fe|Au|G|Ir",
            "Hemijska formula kuhinjske soli je?|NaCl|H2O|CO2|KCl",
            "Koji metal je tečan na sobnoj temperaturi?|živa|olovo|aluminijum|bakar",
            "Na koliko stepeni Celzijusa voda ključa na nivou mora?|100",
            "Na koliko stepeni Celzijusa se voda ledi?|0",
            "Koja planeta je najbliža Suncu?|Merkur|Venera|Mars|Zemlja",
            "Koja je najveća planeta Sunčevog sistema?|Jupiter|Saturn|Neptun|Zemlja",
            "Koja planeta se zove „crvena planeta“?|Mars|Venera|Jupiter|Merkur",
            "Koja planeta je poznata po velikim prstenovima?|Saturn|Mars|Merkur|Venera",
            "Koliko planeta ima Sunčev sistem?|8",
            "Koja je treća planeta od Sunca?|Zemlja|Mars|Venera|Jupiter",
            "Kako se zove Zemljin prirodni satelit?|Mesec|Sunce|Fobos|Titan",
            "Za koliko dana Zemlja obiđe Sunce (otprilike)?|365",
            "Za koliko sati se Zemlja okrene oko svoje ose (otprilike)?|24",
            "Kako se zove naša galaksija?|Mlečni put|Andromeda|Orion|Veliki medved",
            "Šta je Sunce?|zvezda|planeta|kometa|satelit",
            "Koja je najviša planina na svetu?|Mont Everest|K2|Mon Blan|Kilimandžaro",
            "Koji je najveći okean?|Tihi okean|Atlantski okean|Indijski okean|Severni ledeni okean",
            "Koja je najveća vruća pustinja na svetu?|Sahara|Gobi|Kalahari|Atakama",
            "Kako se zove otopljena stena koja izlazi iz vulkana?|lava|led|pesak|bazalt",
            "Koje drvo daje žir?|hrast|bukva|lipa|jela",
            "Od koje biljke se pravi čokolada?|kakao|kafa|vanila|šećerna trska",
            "Koje voće je najpoznatiji izvor vitamina C?|pomorandža|banana|kruška|grožđe",
            "Koja biljka se okreće za suncem dok je mlada?|suncokret|ruža|lala|kukuruz",
            "Koja je najtvrđa prirodna materija?|dijamant|gvožđe|granit|kvarc",
            "Koliko stepeni ima pravi ugao?|90",
            "Koliki je zbir uglova u trouglu (u stepenima)?|180",
            "Koliko strana ima šestougao?|6",
            "Koliko strana ima osmougao?|8",
            "Koliko ivica ima kocka?|12",
            "Koliko temena ima kocka?|8",
            "Koliko strana ima kocka?|6",
            "Koji je najmanji prost broj?|2",
            "Koliko metara ima jedan kilometar?|1000",
            "Koliko je pi zaokruženo na dve decimale?|3,14|3,41|3,12|2,72",
    };

    static final String[] GDE_SE_NALAZI = {
            "U kom gradu se nalazi Ajfelov toranj?|Pariz|London|Rim|Brisel",
            "U kom gradu se nalazi Koloseum?|Rim|Atina|Milano|Napulj",
            "U kom gradu se nalazi Big Ben?|London|Pariz|Dablin|Edinburg",
            "U kom gradu se nalazi Kip slobode?|Njujork|Vašington|Čikago|Boston",
            "U kom gradu se nalazi Akropolj?|Atina|Rim|Solun|Istanbul",
            "U kom gradu se nalazi Sagrada Familija?|Barselona|Madrid|Sevilja|Valensija",
            "U kojoj državi se nalazi Tadž Mahal?|Indija|Pakistan|Iran|Egipat",
            "U kojoj državi se nalaze piramide u Gizi?|Egipat|Meksiko|Sudan|Maroko",
            "U kojoj državi se nalazi Veliki kineski zid?|Kina|Japan|Mongolija|Koreja",
            "U kojoj državi se nalazi Maču Pikču?|Peru|Meksiko|Čile|Kolumbija",
            "U kom gradu se nalazi Kosi toranj?|Piza|Firenca|Venecija|Rim",
            "U kom gradu se nalazi Brandenburška kapija?|Berlin|Beč|Minhen|Hamburg",
            "U kom gradu se nalazi Crveni trg?|Moskva|Sankt Peterburg|Kijev|Minsk",
            "U kojoj državi se nalazi čuvena Opera u Sidneju?|Australija|Novi Zeland|Kanada|Južna Afrika",
            "U kom gradu se nalazi kip Hrista Iskupitelja?|Rio de Žaneiro|Buenos Ajres|Lisabon|Lima",
            "U kom gradu se nalazi Burdž Kalifa, najviša zgrada na svetu?|Dubai|Doha|Rijad|Abu Dabi",
            "U kom gradu se nalazi Karlov most?|Prag|Budimpešta|Beč|Krakov",
            "U kom gradu se nalazi Ermitaž?|Sankt Peterburg|Moskva|Varšava|Riga",
            "U kom gradu se nalazi muzej Prado?|Madrid|Barselona|Lisabon|Rim",
            "U kojoj državi se nalazi Stounhendž?|Velika Britanija|Irska|Francuska|Norveška",
            "U kojoj državi se nalazi Alhambra?|Španija|Portugalija|Maroko|Italija",
            "U kojoj državi se nalazi dvorac Nojšvanštajn?|Nemačka|Austrija|Švajcarska|Francuska",
            "U kojoj državi se nalazi bazilika Svetog Petra?|Vatikan|Francuska|Malta|San Marino",
            "Na granici kojih država su Nijagarini vodopadi?|SAD i Kanade|SAD i Meksika|Brazila i Argentine|Kanade i Danske",
            "U kom gradu se nalazi Hram Svetog Save?|Beograd|Novi Sad|Niš|Kragujevac",
            "U kom gradu se nalazi Petrovaradinska tvrđava?|Novi Sad|Beograd|Smederevo|Subotica",
            "U kom gradu se nalazi Ćele kula?|Niš|Leskovac|Vranje|Kruševac",
            "U kom gradu se nalazi Kalemegdan?|Beograd|Novi Sad|Niš|Kragujevac",
            "Kod kog grada se nalazi Gamzigrad (Feliks Romulijana)?|Zaječar|Niš|Čačak|Valjevo",
            "Na kojoj reci se nalazi Golubačka tvrđava?|Dunav|Sava|Drina|Morava",
            "U kom gradu se nalazi Smederevska tvrđava?|Smederevo|Požarevac|Golubac|Pančevo",
            "U kojoj državi se nalazi Đavolja varoš?|Srbija|Crna Gora|Bosna i Hercegovina|Hrvatska",
            "U kojoj državi se nalaze Plitvička jezera?|Hrvatska|Slovenija|Bosna i Hercegovina|Srbija",
            "U kojoj državi se nalazi Kotor?|Crna Gora|Hrvatska|Albanija|Srbija",
            "U kojoj državi se nalazi Bled sa ostrvom na jezeru?|Slovenija|Austrija|Hrvatska|Italija",
            "U kom gradu se nalazi Stari most na Neretvi?|Mostar|Sarajevo|Višegrad|Banja Luka",
            "U kom gradu se nalazi most Mehmed-paše Sokolovića?|Višegrad|Mostar|Sarajevo|Zvornik",
            "U kom gradu se nalazi Dioklecijanova palata?|Split|Dubrovnik|Zadar|Rijeka",
            "Na kojoj planini se nalazi Avalski toranj?|Avala|Kosmaj|Fruška gora|Rudnik",
            "Na kojoj planini se nalazi Pančićev vrh?|Kopaonik|Zlatibor|Tara|Stara planina",
            "Kroz koji od ovih glavnih gradova protiče Dunav?|Beograd|Prag|Zagreb|Rim",
            "Na kojoj reci leži Pariz?|Sena|Rajna|Loara|Temza",
            "Na kojoj reci leži London?|Temza|Sena|Dunav|Rajna",
            "Na kojoj reci leži Rim?|Tibar|Po|Arno|Dunav",
            "Na kojoj reci leži Novi Sad?|Dunav|Sava|Tisa|Morava",
            "Na kojoj reci leži Niš?|Nišava|Ibar|Drina|Tisa",
            "Na kojoj reci leži Zagreb?|Sava|Drava|Dunav|Kupa",
            "Na kojoj reci leži Prag?|Vltava|Dunav|Laba|Odra",
            "Na ušću koje dve reke leži Beograd?|Save i Dunava|Drine i Save|Morave i Dunava|Tise i Dunava",
            "Koja reka čini veći deo granice između Srbije i Bosne i Hercegovine?|Drina|Sava|Una|Morava",
            "Koja je najduža reka u Evropi?|Volga|Dunav|Rajna|Dnjepar",
            "Na kom kontinentu je pustinja Sahara?|Afrika|Azija|Australija|Južna Amerika",
            "Na kom kontinentu je reka Amazon?|Južna Amerika|Afrika|Azija|Severna Amerika",
            "Na kom kontinentu su planine Himalaji?|Azija|Evropa|Afrika|Južna Amerika",
            "Na kom kontinentu su Ande?|Južna Amerika|Severna Amerika|Azija|Afrika",
            "Gde se nalazi Mrtvo more?|na Bliskom istoku|u Africi|u južnoj Americi|u Skandinaviji",
            "Koje more je između Italije i Balkana?|Jadransko more|Crno more|Egejsko more|Baltičko more",
            "Koje more zapljuskuje Rumuniju i Bugarsku?|Crno more|Jadransko more|Egejsko more|Severno more",
            "U kom moru je ostrvo Krit?|Sredozemnom moru|Crnom moru|Severnom moru|Baltičkom moru",
            "Koji okean je između Evrope i Severne Amerike?|Atlantski|Tihi|Indijski|Južni",
            "Na kom ostrvu je Havana?|Kuba|Jamajka|Haiti|Portoriko",
            "Koja je najveća država na svetu po površini?|Rusija|Kanada|Kina|SAD",
            "Koja država ima najviše stanovnika na svetu?|Indija|Kina|SAD|Indonezija",
            "Koja je najmanja država na svetu?|Vatikan|Monako|San Marino|Malta",
            "Koja država ima oblik čizme?|Italija|Grčka|Čile|Norveška",
            "Koliko saveznih država imaju SAD?|50",
            "Kroz koliko država protiče Dunav?|10",
            "Koja država se zove i „zemlja izlazećeg sunca“?|Japan|Kina|Koreja|Tajland",
            "Koja država se zove i „zemlja hiljadu jezera“?|Finska|Švedska|Kanada|Norveška",
    };

    static final String[] SRBIJA = {
            "Koji je glavni grad Vojvodine?|Novi Sad|Subotica|Zrenjanin|Pančevo",
            "Koji grad se naziva „srpska Atina“?|Novi Sad|Beograd|Kragujevac|Sremski Karlovci",
            "U kom selu je rođen Nikola Tesla?|Smiljan|Idvor|Mokrin|Ivanjica",
            "U kom selu je rođen Mihajlo Pupin?|Idvor|Smiljan|Tršić|Orašac",
            "U kom selu je rođen Vuk Stefanović Karadžić?|Tršić|Idvor|Smiljan|Orašac",
            "U kom selu je podignut Prvi srpski ustanak?|Orašac|Takovo|Tršić|Topola",
            "Ko je bio vođa Prvog srpskog ustanka?|Karađorđe|Miloš Obrenović|Hajduk Veljko|knez Lazar",
            "Ko je predvodio Drugi srpski ustanak?|Miloš Obrenović|Karađorđe|Stevan Sinđelić|Hajduk Veljko",
            "Koje godine je počeo Prvi srpski ustanak?|1804",
            "Koje godine je bila Kosovska bitka?|1389",
            "Ko je predvodio srpsku vojsku u Kosovskoj bici?|knez Lazar|car Dušan|Stefan Nemanja|kralj Milutin",
            "Ko je bio prvi srpski arhiepiskop?|Sveti Sava|Stefan Prvovenčani|Stefan Nemanja|Sveti Simeon",
            "Koji srpski vladar je doneo Zakonik 1349. godine?|car Dušan|knez Lazar|kralj Milutin|despot Stefan",
            "Ko je osnivač dinastije Nemanjića?|Stefan Nemanja|Sveti Sava|car Dušan|kralj Milutin",
            "Ko je bio komandant u bici na Čegru?|Stevan Sinđelić|Karađorđe|Hajduk Veljko|Janko Katić",
            "Kada se slavi Savindan?|27. januara|6. maja|28. juna|14. januara",
            "Kada je Vidovdan?|28. juna|6. maja|27. januara|19. avgusta",
            "Kada je Đurđevdan?|6. maja|28. juna|19. decembra|27. januara",
            "Kada pravoslavni vernici u Srbiji slave Božić?|7. januara|25. decembra|1. januara|14. januara",
            "Kako se zove srpski narodni instrument sa jednom žicom?|gusle|frula|tamburica|gajde",
            "Koja je valuta u Srbiji?|dinar|evro|marka|forinta",
            "Koliko slova ima srpska azbuka?|30",
            "Koje slovo dolazi posle slova G u azbuci?|D|H|Đ|E",
            "Koje je poslednje slovo azbuke?|Š|Ž|Z|Ć",
            "Koje boje su na zastavi Srbije, odozgo nadole?|crvena, plava, bela|plava, bela, crvena|bela, plava, crvena|crvena, bela, plava",
            "Kako se zove himna Srbije?|Bože pravde|Hej, Sloveni|Tamo daleko|Marš na Drinu",
            "Koja planina je poznata po misterioznoj piramidi kod Sokobanje?|Rtanj|Kopaonik|Tara|Zlatibor",
            "Koji nacionalni park je kanjon Dunava u Srbiji?|Đerdap|Tara|Kopaonik|Fruška gora",
            "Na kojoj planini su brojni fruškogorski manastiri?|Fruška gora|Tara|Zlatibor|Rudnik",
            "Koje je najveće veštačko jezero u Srbiji?|Đerdapsko jezero|Vlasinsko jezero|Palićko jezero|Srebrno jezero",
            "Pored kog grada se nalazi Palićko jezero?|Subotica|Sombor|Kikinda|Novi Sad",
            "Pored kog grada se nalazi Srebrno jezero?|Veliko Gradište|Kladovo|Golubac|Smederevo",
            "U kom mestu se održava Sabor trubača?|Guča|Čačak|Užice|Kraljevo",
            "U kom gradu se održava muzički festival Egzit?|Novi Sad|Beograd|Niš|Subotica",
            "Koji grad je poznat po „Nišvilu“?|Niš|Kragujevac|Novi Sad|Pirot",
            "Po čemu je poznat Pirot?|po ćilimima|po trubačima|po kristalu|po svili",
            "Koji grad je poznat po Zastavinoj fabrici automobila?|Kragujevac|Kraljevo|Čačak|Kruševac",
            "Gde se nalazi Šarganska osmica?|na Mokroj Gori|na Kopaoniku|u Sremu|na Fruškoj gori",
            "Koja srpska teniserka je osvojila Rolan Garos 2008. godine?|Ana Ivanović|Jelena Janković|Monika Seleš|Jelena Dokić",
            "Ko je osvojio najviše grend slem titula u muškom tenisu?|Novak Đoković|Rafael Nadal|Rodžer Federer|Pit Sampras",
            "Koji košarkaš iz Sombora je proglašen za najboljeg igrača NBA lige?|Nikola Jokić|Vlade Divac|Peđa Stojaković|Bogdan Bogdanović",
            "U kom gradu je rođen Novak Đoković?|Beograd|Novi Sad|Niš|Kraljevo",
            "Koji fudbalski klub je 1991. osvojio Kup šampiona?|Crvena zvezda|Partizan|Vojvodina|Hajduk",
    };

    static final String[] SPORT = {
            "Koliko igrača ima jedan fudbalski tim na terenu?|11",
            "Koliko igrača ima jedan košarkaški tim na terenu?|5",
            "Koliko igrača ima jedan odbojkaški tim na terenu?|6",
            "Koliko igrača, sa golmanom, ima vaterpolo tim u vodi?|7",
            "Koliko igrača, sa golmanom, ima rukometni tim na terenu?|7",
            "Koliko minuta traje jedno poluvreme fudbalske utakmice?|45",
            "Koliko minuta traje jedna četvrtina u FIBA košarci?|10",
            "Koliko poena vredi koš iz slobodnog bacanja?|1",
            "Na kojoj podlozi se igra Vimbldon?|trava|šljaka|beton|tepih",
            "Na kojoj podlozi se igra Rolan Garos?|šljaka|trava|beton|tepih",
            "Koliko grend slem turnira ima u teniskoj sezoni?|4",
            "Gde su održane prve moderne Olimpijske igre 1896. godine?|Atina|Pariz|London|Rim",
            "Koliko krugova ima na olimpijskoj zastavi?|5",
            "Na koliko godina se održavaju Letnje olimpijske igre?|4",
            "Koliko polja ima šahovska tabla?|64",
            "Koja šahovska figura se kreće u obliku slova L?|skakač (konj)|lovac|top|kraljica",
            "Kako se zove potez u šahu kad kralj i top zamene mesta?|rokada|šah-mat|pat|gambit",
            "Koliko kilometara je dugačak maraton (zaokruženo)?|42|40|21|50",
            "Koja zemlja je osvojila najviše Svetskih prvenstava u fudbalu?|Brazil|Nemačka|Italija|Argentina",
            "Koliko rupa ima standardni teren za golf?|18",
            "Koliko poena vredi tačdaun u američkom fudbalu?|6",
            "Kako se zove pogodak sa tri gola jednog igrača u istoj utakmici?|het-trik|ofsajd|penal|korner",
            "U kom sportu se koristi pak?|hokej na ledu|kriket|badminton|polo",
            "U kom sportu se koristi loptica sa perjem?|badminton|tenis|stoni tenis|skvoš",
            "Koja boja majice označava lidera na Tur de Fransu?|žuta|roze|zelena|bela",
            "Koliko traje jedna runda u profesionalnom boksu (minuta)?|3",
            "Koliko je dugačak bazen za olimpijsko plivanje (metara)?|50",
            "Koliko metara je visok košarkaški obruč?|3,05|2,75|3,50|2,95",
    };

    static final String[] JEZIK = {
            "Kako glasi množina reči „čovek“?|ljudi|čoveci|čovekovi|čovečani",
            "Kako glasi množina reči „dete“?|deca|deti|detići|detovi",
            "Kako glasi množina reči „oko“?|oči|oka|okovi|oćevi",
            "Kako glasi množina reči „uho“?|uši|uha|uhovi|ušovi",
            "Koja reč znači isto što i „hrabar“?|smeo|plašljiv|lenj|tih",
            "Koja reč znači isto što i „brz“?|hitar|spor|težak|tih",
            "Koja reč je suprotna od „vredan“?|lenj|marljiv|pametan|veseo",
            "Koja reč je suprotna od „širok“?|uzak|dug|visok|debeo",
            "Koja reč je suprotna od „mudar“?|glup|pametan|star|tih",
            "Šta znači izraz „pala mu je sekira u med“?|imao je sreće|povredio se|izgubio je posao|pokvario je nešto",
            "Šta znači izraz „gledati kroz prste“?|praštati nešto|loše videti|krasti|igrati se",
            "Šta znači izraz „obesiti o klin“?|prestati sa nečim|okačiti kaput|sakriti nešto|kazniti nekoga",
            "Šta znači izraz „baciti pušku u šaš“?|odustati|ići u lov|sakriti se|pobediti",
            "Šta znači izraz „ni luk jeo, ni luk mirisao“?|praviti se nevešt|ne voleti luk|biti gladan|biti umoran",
            "Šta znači izraz „kupiti mačka u džaku“?|kupiti nešto neprovereno|kupiti ljubimca|uštedeti novac|prevariti nekoga",
            "Kako se završava poslovica „Ko rano rani…“?|dve sreće grabi|taj kasno legne|dobro spava|ostaje gladan",
            "Kako se završava poslovica „Bez muke…“?|nema nauke|nema hleba|nema sreće|nema druga",
            "Kako se završava poslovica „Ko drugome jamu kopa…“?|sam u nju pada|lopatu nosi|dobro radi|ne spava",
            "Kako se završava poslovica „Ne pada sneg da pokrije breg, nego…“?|da svaka zverka pokaže svoj trag|da deca imaju sanke|da bude zima|da se sakrije trava",
            "Kako se završava poslovica „Ispeci, pa…“?|reci|pojedi|podeli|ćuti",
            "Kako se završava poslovica „Gde ima dima…“?|ima i vatre|ima i kiše|nema vazduha|ima i ljudi",
            "Kako se završava poslovica „Sto ljudi…“?|sto ćudi|sto puta|sto kuća|sto želja",
            "Koliko slogova ima reč „pomorandža“?|4",
            "Koliko slogova ima reč „telefon“?|3",
            "Koliko slova ima reč „džemper“ napisana ćirilicom?|6",
            "Koja od ovih reči je napisana pravilno?|uopšte|uobšte|u opšte|uopšťe",
            "Koja od ovih reči je napisana pravilno?|odjednom|od jednom|odjedno|otjednom",
            "Koja od ovih reči je napisana pravilno?|podsetnik|potsetnik|pod setnik|podssetnik",
            "Koja od ovih reči je napisana pravilno?|predsednik|pretsednik|presednik|predsjednik",
            "Kako se kaže „hello“ na srpskom?|zdravo|hvala|izvini|doviđenja",
            "Šta znači engleska reč „window“?|prozor|vrata|zid|krov",
            "Šta znači engleska reč „library“?|biblioteka|laboratorija|knjižara i kafić|škola",
            "Šta znači nemačka reč „Danke“?|hvala|zdravo|molim|izvini",
            "Šta znači italijanska reč „ciao“?|zdravo ili ćao|hvala|molim|laku noć",
            "Šta znači španska reč „gracias“?|hvala|zdravo|dobro jutro|prijatno",
            "Šta znači francuska reč „bonjour“?|dobar dan|laku noć|hvala|doviđenja",
    };

    static final String[] VALUTE = {
            "Koja je valuta u Japanu?|jen|juan|von|rupija",
            "Koja je valuta u Velikoj Britaniji?|funta|evro|dolar|kruna",
            "Koja je valuta u SAD?|dolar|funta|evro|peso",
            "Koja je valuta u Švajcarskoj?|franak|evro|kruna|marka",
            "Koja je valuta u Rusiji?|rublja|grivna|zlot|lev",
            "Koja je valuta u Kini?|juan|jen|von|rupija",
            "Koja je valuta u Indiji?|rupija|juan|dinar|taka",
            "Koja je valuta u Bosni i Hercegovini?|konvertibilna marka|dinar|evro|kuna",
            "Koja je valuta u Mađarskoj?|forinta|evro|kruna|lej",
            "Koja je valuta u Hrvatskoj?|evro|kuna|dinar|marka",
            "Koja je valuta u Poljskoj?|zlot|forinta|kruna|evro",
            "Koja je valuta u Češkoj?|kruna|zlot|evro|forinta",
            "Koja je valuta u Turskoj?|lira|dinar|drahma|rial",
            "Koja je valuta u Rumuniji?|lej|lev|forinta|evro",
            "Koja je valuta u Severnoj Makedoniji?|denar|dinar|evro|lek",
            "Koja je valuta u Meksiku?|peso|dolar|real|sol",
            "Koja je valuta u Brazilu?|real|peso|dolar|eskudo",
            "Koja je valuta u Ukrajini?|grivna|rublja|zlot|lej",
            "Koja je valuta u Švedskoj?|kruna|evro|funta|franak",
            "Koja je valuta u Crnoj Gori?|evro|dinar|marka|lek",
    };

    /** Nazivi grupa, istim redom kao GROUPS. */
    static final String[] NAMES = {
            "Zagonetka", "Pitalica", "Opšta kultura", "Književnost", "Priroda i nauka",
            "Gde se nalazi", "Srbija", "Sport", "Jezik", "Valute",
    };

    static final String[][] GROUPS = {
            ZAGONETKE, PITALICE, OPSTA_KULTURA, KNJIZEVNOST, PRIRODA,
            GDE_SE_NALAZI, SRBIJA, SPORT, JEZIK, VALUTE,
    };

    static final String[] CONTINENTS = {
            "Evropa", "Azija", "Afrika", "Severna Amerika", "Južna Amerika", "Australija i Okeanija",
    };

    /**
     * „Država|glavni grad|kontinent“. Kontinent se izostavlja kod država koje su na dva kontinenta,
     * pa se za njih ne postavlja pitanje o kontinentu. Izostavljene su države čiji se glavni grad
     * zove isto kao država ili oko kog postoji spor.
     */
    static final String[] COUNTRIES = {
            "Srbija|Beograd|Evropa",
            "Hrvatska|Zagreb|Evropa",
            "Bosna i Hercegovina|Sarajevo|Evropa",
            "Crna Gora|Podgorica|Evropa",
            "Severna Makedonija|Skoplje|Evropa",
            "Slovenija|Ljubljana|Evropa",
            "Bugarska|Sofija|Evropa",
            "Rumunija|Bukurešt|Evropa",
            "Mađarska|Budimpešta|Evropa",
            "Grčka|Atina|Evropa",
            "Albanija|Tirana|Evropa",
            "Italija|Rim|Evropa",
            "Francuska|Pariz|Evropa",
            "Nemačka|Berlin|Evropa",
            "Austrija|Beč|Evropa",
            "Švajcarska|Bern|Evropa",
            "Španija|Madrid|Evropa",
            "Portugalija|Lisabon|Evropa",
            "Velika Britanija|London|Evropa",
            "Irska|Dablin|Evropa",
            "Holandija|Amsterdam|Evropa",
            "Belgija|Brisel|Evropa",
            "Danska|Kopenhagen|Evropa",
            "Švedska|Stokholm|Evropa",
            "Norveška|Oslo|Evropa",
            "Finska|Helsinki|Evropa",
            "Island|Rejkjavik|Evropa",
            "Poljska|Varšava|Evropa",
            "Češka|Prag|Evropa",
            "Slovačka|Bratislava|Evropa",
            "Ukrajina|Kijev|Evropa",
            "Belorusija|Minsk|Evropa",
            "Litvanija|Viljnus|Evropa",
            "Letonija|Riga|Evropa",
            "Estonija|Talin|Evropa",
            "Moldavija|Kišinjev|Evropa",
            "Malta|Valeta|Evropa",
            "Rusija|Moskva",
            "Turska|Ankara",
            "Kipar|Nikozija",
            "Gruzija|Tbilisi",
            "Jermenija|Jerevan",
            "Azerbejdžan|Baku",
            "Kazahstan|Astana",
            "Kina|Peking|Azija",
            "Japan|Tokio|Azija",
            "Južna Koreja|Seul|Azija",
            "Severna Koreja|Pjongjang|Azija",
            "Indija|Nju Delhi|Azija",
            "Pakistan|Islamabad|Azija",
            "Bangladeš|Daka|Azija",
            "Nepal|Katmandu|Azija",
            "Tajland|Bangkok|Azija",
            "Vijetnam|Hanoj|Azija",
            "Filipini|Manila|Azija",
            "Malezija|Kuala Lumpur|Azija",
            "Mongolija|Ulan Bator|Azija",
            "Uzbekistan|Taškent|Azija",
            "Avganistan|Kabul|Azija",
            "Iran|Teheran|Azija",
            "Irak|Bagdad|Azija",
            "Sirija|Damask|Azija",
            "Liban|Bejrut|Azija",
            "Jordan|Aman|Azija",
            "Saudijska Arabija|Rijad|Azija",
            "Ujedinjeni Arapski Emirati|Abu Dabi|Azija",
            "Katar|Doha|Azija",
            "Kambodža|Pnom Pen|Azija",
            "Laos|Vijentijan|Azija",
            "Egipat|Kairo|Afrika",
            "Maroko|Rabat|Afrika",
            "Libija|Tripoli|Afrika",
            "Nigerija|Abudža|Afrika",
            "Gana|Akra|Afrika",
            "Kenija|Najrobi|Afrika",
            "Etiopija|Adis Abeba|Afrika",
            "Tanzanija|Dodoma|Afrika",
            "Uganda|Kampala|Afrika",
            "Angola|Luanda|Afrika",
            "Senegal|Dakar|Afrika",
            "Sudan|Kartum|Afrika",
            "Zimbabve|Harare|Afrika",
            "Zambija|Lusaka|Afrika",
            "Madagaskar|Antananarivo|Afrika",
            "Kamerun|Jaunde|Afrika",
            "Mali|Bamako|Afrika",
            "Demokratska Republika Kongo|Kinšasa|Afrika",
            "Ruanda|Kigali|Afrika",
            "Somalija|Mogadiš|Afrika",
            "Mozambik|Maputo|Afrika",
            "Namibija|Vindhuk|Afrika",
            "Bocvana|Gaborone|Afrika",
            "SAD|Vašington|Severna Amerika",
            "Kanada|Otava|Severna Amerika",
            "Meksiko|Meksiko Siti|Severna Amerika",
            "Kuba|Havana|Severna Amerika",
            "Jamajka|Kingston|Severna Amerika",
            "Kostarika|San Hoze|Severna Amerika",
            "Honduras|Tegusigalpa|Severna Amerika",
            "Nikaragva|Managva|Severna Amerika",
            "Dominikanska Republika|Santo Domingo|Severna Amerika",
            "Haiti|Port o Prens|Severna Amerika",
            "Brazil|Brazilija|Južna Amerika",
            "Argentina|Buenos Ajres|Južna Amerika",
            "Čile|Santjago|Južna Amerika",
            "Peru|Lima|Južna Amerika",
            "Kolumbija|Bogota|Južna Amerika",
            "Venecuela|Karakas|Južna Amerika",
            "Ekvador|Kito|Južna Amerika",
            "Paragvaj|Asunsion|Južna Amerika",
            "Urugvaj|Montevideo|Južna Amerika",
            "Australija|Kanbera|Australija i Okeanija",
            "Novi Zeland|Velington|Australija i Okeanija",
            "Fidži|Suva|Australija i Okeanija",
            "Papua Nova Gvineja|Port Morzbi|Australija i Okeanija",
    };
}
